In [1]:
import pandas as pd
import json
import sys
sys.path.append("..")
import os

# Load public tables and our pdb lists

In [ ]:
prem_pdb_list = [f.split('.')[0] for f in os.listdir("../../GraPPI_data/curated_db/unmut_sthg_8A/")]
S90_list = [line.strip('\n') for line in open("./saved_tables/S90_list.txt")]
S79_df = pd.read_csv("./saved_tables/S79_table.csv")
SKEMPI_df = pd.read_csv("./saved_tables/SKEMPI_test_table.csv")
mut_df = pd.read_csv("./saved_tables/mutant_table.csv")
raw_dimer_db = pd.read_csv("./saved_tables/nr_dimer_table_foldseek_cov08_tms08_exh.csv")
dimer_db = pd.read_csv("./saved_tables/dimer_table.csv")

In [4]:
dimer_db

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,1AKH,A,B,../../PDB/new_dimer_db/1AKH.pdb,1.0
1,1B34,A,B,../../PDB/new_dimer_db/1B34.pdb,1.0
2,1BND,A,B,../../PDB/new_dimer_db/1BND.pdb,1.0
3,1CF7,A,B,../../PDB/new_dimer_db/1CF7.pdb,1.0
4,1CI6,A,B,../../PDB/new_dimer_db/1CI6.pdb,1.0
...,...,...,...,...,...
8686,7CD9,A,B,../../PDB/old_dimer_db/7CD9.pdb,1.0
8687,7CKF,A,B,../../PDB/old_dimer_db/7CKF.pdb,1.0
8688,7NBI,A,B,../../PDB/old_dimer_db/7NBI.pdb,1.0
8689,7NDL,A,B,../../PDB/old_dimer_db/7NDL.pdb,1.0
8690,5XSP,A,B,../../PDB/old_dimer_db/5XSP.pdb,1.0

### Get dimer db if it's not prepared

In [3]:
raw_dimer_db

,PDB,chain_1,chain_2,path,source,cluster_rep,cluster_size,is_representative
0,1AKH,A,B,../../PDB/new_dimer_db/1AKH.pdb,new_dimer_db,1AKH,3,True
1,1B34,A,B,../../PDB/new_dimer_db/1B34.pdb,new_dimer_db,1B34,1,True
2,1BND,A,B,../../PDB/new_dimer_db/1BND.pdb,new_dimer_db,1BND,3,True
3,1CF7,A,B,../../PDB/new_dimer_db/1CF7.pdb,new_dimer_db,1CF7,1,True
4,1CI6,A,B,../../PDB/new_dimer_db/1CI6.pdb,new_dimer_db,1CI6,1,True
...,...,...,...,...,...,...,...,...
9372,7CD9,A,B,../../PDB/old_dimer_db/7CD9.pdb,old_dimer_db,7CD9,1,True
9373,7CKF,A,B,../../PDB/old_dimer_db/7CKF.pdb,old_dimer_db,7CKF,2,True
9374,7NBI,A,B,../../PDB/old_dimer_db/7NBI.pdb,old_dimer_db,7NBI,1,True
9375,7NDL,A,B,../../PDB/old_dimer_db/7NDL.pdb,old_dimer_db,7NDL,2,True
9376,5XSP,A,B,../../PDB/old_dimer_db/5XSP.pdb,old_dimer_db,5XSP,1,True

In [4]:
exclude_list = list(set([pdb.upper() for pdb in S79_df['PDB'].tolist()]+[pdb.upper() for pdb in S90_list] + [pdb_f.split('.')[0].upper() for pdb_f in prem_pdb_list]\
    + [pdb_m.split('_')[0].upper() for pdb_m in SKEMPI_df[SKEMPI_df['Mutation(s)_PDB']==pd.notna]['#Pdb'].tolist()]))
exclude_list

['1ZSG',
 '1P9D',
 '4Z5R',
 '4XH2',
 '4U32',
 '1MPA',
 '1LX5',
 '2NZ9',
 '5HYS',
 '6CQL',
 '2FJH',
 '3TZ1',
 '2G81',
 '3QEQ',
 '1ZVH',
 '2B12',
 '4G01',
 '1EER',
 '6FUD',
 '2F5Z',
 '6B0S',
 '3ORV',
 '4FQV',
 '3EG5',
 '3P0Y',
 '5V5I',
 '2GAF',
 '4P2O',
 '5HPY',
 '2EH8',
 '5C3F',
 '5W6G',
 '5DJT',
 '4ZFG',
 '3NOG',
 '4JEH',
 '4J2Y',
 '6FP7',
 '5BK1',
 '2K8F',
 '5DH9',
 '5A3I',
 '3SJA',
 '1N8O',
 '6C16',
 '4G6U',
 '5FFO',
 '4X7S',
 '3VV2',
 '4GN3',
 '2HTH',
 '3SKJ',
 '3DBL',
 '3D5S',
 '3QWQ',
 '5MJ3',
 '5LXQ',
 '5VEY',
 '5SWK',
 '5F5S',
 '5JEM',
 '3BT1',
 '6B0A',
 '5XWT',
 '5SX5',
 '1DZB',
 '5TL7',
 '6DMX',
 '4YPI',
 '5NQF',
 '1AHW',
 '5NWM',
 '3KPS',
 '2N2H',
 '3TPU',
 '2Z7F',
 '3R4D',
 '5V5H',
 '4C1N',
 '3KJ2',
 '2V51',
 '6OAN',
 '3OGO',
 '3QSK',
 '2YVJ',
 '2F31',
 '1JSP',
 '4X7D',
 '3HFM',
 '4YC7',
 '1L4D',
 '6B5O',
 '1QUR',
 '1P2C',
 '6B6U',
 '2Z34',
 '2WG4',
 '4BFI',
 '6OSW',
 '3WA5',
 '5XIS',
 '1FO0',
 '3F5C',
 '4CVW',
 '2JEL',
 '4W4O',
 '5MYK',
 '4HRL',
 '4ERS',
 '3BTT',
 '6NE1',
 '5GRJ',
 '2VLP',
 '5JHL',
 '4BPK',
 '4LMQ',
 '4IZ7',
 '5E94',
 '5VZM',
 '3S8V',
 '2W2M',
 '6H0E',
 '3IET',
 '1MWA',
 '4I2X',
 '4PJE',
 '1XD3',
 '4QOK',
 '4MQW',
 '1XGU',
 '4DH2',
 '3BE1',
 '4JRX',
 '2NY4',
 '3AY4',
 '1EWY',
 '3R1G',
 '3UKZ',
 '5IP4',
 '5EG3',
 '4WFD',
 '4KDI',
 '2WG3',
 '3QDJ',
 '4YBL',
 '6DKJ',
 '3DVG',
 '6C48',
 '4YVQ',
 '3TGK',
 '3IXT',
 '4KT3',
 '2Y6T',
 '4IOF',
 '2A9K',
 '3DVU',
 '5F4E',
 '2XZQ',
 '3QHT',
 '1FQJ',
 '4MI8',
 '3SQO',
 '4GLA',
 '6H6Y',
 '3VEP',
 '4WNN',
 '5BOZ',
 '4UI1',
 '1NBY',
 '6J5D',
 '2VOG',
 '5D1X',
 '4LGP',
 '5J7C',
 '1NCA',
 '5TAR',
 '3Q3G',
 '6F2G',
 '1U7V',
 '5W9A',
 '5MFC',
 '4F9L',
 '1N8Z',
 '5E6P',
 '6IUA',
 '1MCV',
 '5LQB',
 '4YK4',
 '5J8H',
 '1T6B',
 '5K22',
 '5EU6',
 '4XI5',
 '5C07',
 '5L6N',
 '1JH4',
 '1AVX',
 '3BTF',
 '4F9P',
 '5T6L',
 '4NM8',
 '1T0P',
 '5WHK',
 '6DDM',
 '1VSQ',
 '3TJZ',
 '5TWA',
 '6ILK',
 '3EBA',
 '1TM5',
 '4KRO',
 '1WDW',
 '6FPG',
 '5SWS',
 '1TM4',
 '1TBR',
 '1B6C',
 '1T01',
 '2P1L',
 '4DVG',
 '6FLB',
 '1TBA',
 '1ID5',
 '4G8G',
 '4FQR',
 '3P9W',
 '3MV9',
 '5EE4',
 '4ZLT',
 '3GHE',
 '5J13',
 '5H3J',
 '3CX6',
 '4PWX',
 '5M2J',
 '1IQD',
 '6P50',
 '1H59',
 '1USU',
 '4ZGY',
 '6BKD',
 '4M8Q',
 '3BIW',
 '4G6V',
 '6AXK',
 '6JWJ',
 '1RV6',
 '5N48',
 '1JMO',
 '5TKJ',
 '6IW8',
 '6HT9',
 '6GBU',
 '1TT5',
 '5LZ6',
 '5YIP',
 '2CMR',
 '1P6A',
 '2WP0',
 '1ZLI',
 '2MLY',
 '1YX5',
 '2PON',
 '3TAC',
 '6Q18',
 '3BX7',
 '1LQB',
 '5KVG',
 '5ET1',
 '4JMF',
 '2LNK',
 '2O3B',
 '1AN1',
 '5O76',
 '3D5O',
 '3TL8',
 '5U8Q',
 '4ZGQ',
 '6E4Y',
 '1TBQ',
 '4RWS',
 '5NMV',
 '2VWE',
 '5C67',
 '3PL6',
 '3HI1',
 '5Y80',
 '3MJ9',
 '6FLC',
 '4HS6',
 '6ORQ',
 '5Y1Z',
 '6NMT',
 '2VLQ',
 '3IDX',
 '1WPX',
 '5NT7',
 '3VZA',
 '2P5T',
 '4NN6',
 '5ABV',
 '2AST',
 '6BKC',
 '2B2W',
 '6A78',
 '5OHP',
 '1BD2',
 '4CU4',
 '3Q9N',
 '4EEF',
 '3UII',
 '4GUR',
 '2Y06',
 '1AO7',
 '3LAQ',
 '5KW9',
 '2PX9',
 '6JCS',
 '1MZW',
 '3LZF',
 '2M0G',
 '2C7N',
 '2OI9',
 '6MUD',
 '5D1Q',
 '3P6Z',
 '1TZI',
 '5MYX',
 '1EZU',
 '6II9',
 '3V96',
 '6MC9',
 '4HH3',
 '6MLK',
 '3MJ7',
 '2FYL',
 '3LB8',
 '5LCV',
 '5KVD',
 '4G59',
 '1G6R',
 '1BQL',
 '5HU3',
 '5D93',
 '4J4P',
 '5FV2',
 '4CJ2',
 '4AUQ',
 '2LZ6',
 '1G6V',
 '3UAI',
 '1GO4',
 '5VPL',
 '4KHX',
 '5AJK',
 '3D5R',
 '3ALZ',
 '5JJD',
 '5XDA',
 '1F7Z',
 '6IEA',
 '4X7F',
 '1XX9',
 '2HSQ',
 '3M62',
 '5D70',
 '2WUC',
 '1Y6K',
 '3QUX',
 '2P46',
 '3REB',
 '2FTL',
 '1TM3',
 '6FG2',
 '4YHP',
 '1GC1',
 '4WHT',
 '3BTD',
 '4KT1',
 '5J4A',
 '6JEP',
 '5NL1',
 '1FLE',
 '6O8B',
 '5VT9',
 '3UZ0',
 '5ONA',
 '3OUX',
 '2R0K',
 '4K2U',
 '3L33',
 '5BW8',
 '5KHO',
 '5FOB',
 '3CX8',
 '2JJT',
 '5EQL',
 '2PHE',
 '6ORO',
 '4K5A',
 '6HHC',
 '5AOQ',
 '6B0E',
 '3B23',
 '2WH6',
 '2DSQ',
 '4JW2',
 '5X60',
 '2VN5',
 '3AA6',
 '1TAW',
 '4HMY',
 '4GIQ',
 '4QY8',
 '3SJD',
 '4V2C',
 '3PMH',
 '1R6Q',
 '4WO4',
 '4FP8',
 '3TKL',
 '2ONL',
 '3FIE',
 '1L0Y',
 '5JYL',
 '4K1R',
 '4XL5',
 '2KVQ',
 '6NMR',
 '6ER6',
 '5DCQ',
 '6AAF',
 '4OQT',
 '5E8E',
 '1VET',
 '4HWB',
 '1RKE',
 '4APF',
 '5YDR',
 '5H07',
 '3KUD',
 '3IXS',
 '1RPQ',
 '5MU3',
 '5JW9',
 '5G1X',
 '1PSB',
 '3TWI',
 '3OL2',
 '2ZVN',
 '2W81',
 '1UL1',
 '4DZU',
 '1WLP',
 '6GFI',
 '5BW7',
 '5ML9',
 '5TKK',
 '3CRK',
 '1WQ1',
 '2P49',
 '5UA4',
 '4MRT',
 '2LEH',
 '2LQH',
 '4M1D',
 '4LAD',
 '1KKL',
 '1IB1',
 '5GJK',
 '2MUR',
 '6MSL',
 '3C5T',
 '1DP5',
 '1P4B',
 '4U97',
 '6O1F',
 '4OYD',
 '6H15',
 '3UKX',
 '3ZO0',
 '5CJS',
 '4KT5',
 '1JCK',
 '4IYP',
 '4NL9',
 '2XTT',
 '6B3M',
 '6D6U',
 '2Q7N',
 '6N5W',
 '5JTQ',
 '4JW3',
 '2A6D',
 '3V62',
 '5D7J',
 '4M62',
 '1HRT',
 '4P23',
 '5CIN',
 '4YJ4',
 '1MHH',
 '4ZI2',
 '3BLH',
 '5ME5',
 '4CC4',
 '3GQI',
 '1LP1',
 '5MYO',
 '2GYK',
 '6A7V',
 '4EUK',
 '1UUG',
 '2WO2',
 '3AJB',
 '4IHH',
 '1OP9',
 '1VEU',
 '3IU3',
 '4ZPT',
 '6J14',
 '1TMG',
 '4ONS',
 '5UQ3',
 '2OUL',
 '4LN0',
 '2K8C',
 '5CIL',
 '3ZRZ',
 '1SHZ',
 '3PVM',
 '2Y8T',
 '3TG1',
 '4CMH',
 '1LQS',
 '6GBG',
 '5C6T',
 '4NU1',
 '1WR1',
 '2WX0',
 '6FV0',
 '4THN',
 '5O05',
 '2N8J',
 '2B42',
 '2Y07',
 '4E05',
 '4KVN',
 '4E6K',
 '4JG0',
 '5H6R',
 '5TE4',
 '3IDC',
 '4EIZ',
 '5SXP',
 '2OMV',
 '1USV',
 '1M5N',
 '6Q0H',
 '5D3I',
 '3KLS',
 '5T6P',
 '2A6I',
 '1DIT',
 '1KIP',
 '3GJ8',
 '2NU4',
 '2IFF',
 '2W2N',
 '1B2S',
 '4PZ6',
 '5K8Q',
 '2UXN',
 '5C08',
 '4PJX',
 '1I8I',
 '5SZH',
 '1OZS',
 '1LZW',
 '4E41',
 '6E3I',
 '5J57',
 '5MV9',
 '6B12',
 '1E6J',
 '2J4W',
 '3JVF',
 '1J7V',
 '1WEJ',
 '6NFJ',
 '2Q0O',
 '5FZT',
 '3N0P',
 '6FUZ',
 '1S4Y',
 '1H1V',
 '4KHT',
 '2B87',
 '3U0T',
 '3LMS',
 '5C0B',
 '4MIT',
 '3SJH',
 '5CX3',
 '4ZFO',
 '2VDA',
 '1VYT',
 '2W80',
 '4WWI',
 '4KGQ',
 '3RTQ',
 '4ZRK',
 '6BXA',
 '2L29',
 '6M7L',
 '4PJG',
 '4JEU',
 '1T63',
 '2A6K',
 '6PHB',
 '4ZS7',
 '5D1M',
 '2POP',
 '5CD5',
 '3ZS9',
 '6AW2',
 '1L8C',
 '5XQZ',
 '4YWC',
 '1XGT',
 '5WKO',
 '5TFW',
 '4C7N',
 '2IHS',
 '2IJO',
 '2OMZ',
 '4NG2',
 '1NB5',
 '3MV7',
 '5XSQ',
 '3LEV',
 '4XKL',
 '3EYU',
 '2B11',
 '4IOS',
 '5IJ0',
 '6KBN',
 '2LXP',
 '1ACB',
 '6BIT',
 '2LP0',
 '3OHM',
 '2SGP',
 '4F3F',
 '3U43',
 '2JZN',
 '3IXA',
 '3NGB',
 '2OOR',
 '6CQQ',
 '3LNZ',
 '5EP6',
 '4D0N',
 '1YQV',
 '6OAO',
 '5EO9',
 '1OC0',
 '5CFF',
 '2R0Z',
 '4HJJ',
 '2FEW',
 '2FJU',
 '5U7O',
 '4WEU',
 '3O6Q',
 '3OWT',
 '5L8J',
 '5AGW',
 '4QTI',
 '6CE9',
 '4UUZ',
 '3QT2',
 '2VLO',
 '3WRY',
 '4BQD',
 '4GN4',
 '4OJK',
 '4JAN',
 '1CLV',
 '6FE4',
 '3U82',
 '3BN3',
 '2MJ5',
 '5F3B',
 '5VWY',
 '3UIG',
 '6KM7',
 '1QSE',
 '5D72',
 '1P27',
 '3QIU',
 '3K6G',
 '4PJF',
 '5THP',
 '2H4M',
 '2G2U',
 '3GJ5',
 '4P59',
 '5XJ3',
 '5T5F',
 '5MTM',
 '6GVK',
 '4Y7M',
 '3D7T',
 '1TY4',
 '5VX0',
 '3MCA',
 '3W8I',
 '5G15',
 '4UEM',
 '3G7Z',
 '5EE5',
 '1YX6',
 '1OYH',
 '5BNQ',
 '3TF7',
 '4K9E',
 '2JT4',
 '2NXZ',
 '4G8A',
 '5BQE',
 '6BB4',
 '3GGW',
 '1A2K',
 '6FQ0',
 '3IT8',
 '5YMY',
 '4PER',
 '2J7P',
 '5E3E',
 '5EDV',
 '6DG5',
 '6MGP',
 '5VYF',
 '1F5R',
 '6DC9',
 '3RBB',
 '3BIK',
 '1KIR',
 '6UYS',
 '5MEV',
 '6CDM',
 '6NE2',
 '3RPG',
 '3BH6',
 '6H7N',
 '3NH7',
 '1ZC3',
 '3GD1',
 '4BQ6',
 '1EZS',
 '1F6M',
 '1WR6',
 '5CZF',
 '2YJ1',
 '2CPK',
 '3EYS',
 '4GRL',
 '2OZA',
 '4K71',
 '5TE6',
 '2FJG',
 '5T1D',
 '2HQS',
 '4PGJ',
 '2OMX',
 '2OMU',
 '4ZK9',
 '1NM5',
 '2KDE',
 '3JSV',
 '3E1Z',
 '5MAD',
 '5J3D',
 '6J11',
 '4HCN',
 '1XJ7',
 '3E8U',
 '1NYU',
 '5VKO',
 '4JFE',
 '3R85',
 '3LHP',
 '6E4Z',
 '3DCO',
 '3IM4',
 '1E50',
 '5C0N',
 '1EES',
 '6CWT',
 '3H7B',
 '4PBV',
 '3MZW',
 '3DVN',
 '5N7W',
 '2QUR',
 '2XB6',
 '2C0L',
 '4EKC',
 '2WY3',
 '3DXD',
 '5FOA',
 '6OV2',
 '5GHW',
 '1DQJ',
 '5UFQ',
 '1B2U',
 '4KVG',
 '5M36',
 '1UUZ',
 '5WVO',
 '5NX3',
 '2WP3',
 '1H9D',
 '3GTY',
 '3B2V',
 '2K8B',
 '3WQB',
 '2JTT',
 '2MTA',
 '3VXU',
 '5UK5',
 '2ESV',
 '3EAB',
 '3VFV',
 '2KBW',
 '2W83',
 '2A9H',
 '3OKY',
 '1XXF',
 '3EQS',
 '1F3V',
 '4OD2',
 '2RVB',
 '2YPL',
 '5CMN',
 '1PJN',
 '4AYD',
 '5J11',
 '4UWQ',
 '4WND',
 '2V2W',
 '3HI6',
 '3G5Y',
 '5J28',
 '1FSK',
 '3H3P',
 '1IBR',
 '6F7T',
 '3UL1',
 '6JHW',
 '3SDD',
 '1KGY',
 '2NZ1',
 '4HS8',
 '3SO3',
 '3WWN',
 '1SB0',
 '3FII',
 '3O43',
 '1JGN',
 '5B71',
 '3TNF',
 '2NUP',
 '3BKY',
 '2DJY',
 '2BWE',
 '2VYR',
 '6A0Z',
 '2P47',
 '4PJ2',
 '6FU9',
 '3NOC',
 '4PJH',
 '5X4L',
 '3PC8',
 '3BP8',
 '3LK4',
 '4JFX',
 '5UN7',
 '3PNR',
 '4TQ0',
 '2M49',
 '5ZIA',
 '3HCU',
 '5IKC',
 '2J0T',
 '3P0G',
 '1GL1',
 '3Q4F',
 '5ITZ',
 '5MJY',
 '3REA',
 '1US7',
 '6AKM',
 '5F6K',
 '5XLN',
 '5SWZ',
 '4CJ1',
 '4KP3',
 '5GLH',
 '5HHO',
 '4ODX',
 '3ZJY',
 '6CDO',
 '6O3O',
 '3F7P',
 '2OMT',
 '3VFM',
 '5VPG',
 '3NPZ',
 '2AQ2',
 '4HX3',
 '3M63',
 '1SYQ',
 '6H9N',
 '2K79',
 '3QTL',
 '6BA6',
 '3T6G',
 '4NIQ',
 '5MR5',
 '5OO6',
 '5KVE',
 '6D6T',
 '5JW7',
 '6THG',
 '3EO1',
 '3N06',
 '2LY4',
 '1Y34',
 '1YYM',
 '1NEZ',
 '2Y48',
 '2IY1',
 '4G9F',
 '2I32',
 '3U8X',
 '6KBR',
 '6H2Y',
 '6JDJ',
 '2JCC',
 '2PYE',
 '2SIC',
 '4P6I',
 '4DCK',
 '1YYL',
 '3RO2',
 '4IW4',
 '3KW5',
 '3SDC',
 '5UWU',
 '5TH9',
 '3CQC',
 '3ONA',
 '1FMO',
 '5USL',
 '2WQZ',
 '1E96',
 '4B1V',
 '1CZ8',
 '3ZU7',
 '3VFN',
 '4GEQ',
 '1TZN',
 '4DAY',
 '1ZHI',
 '3G3B',
 '1X1W',
 '3SE9',
 '6BYH',
 '5JTR',
 '4PJB',
 '5GIM',
 '2PCC',
 '5HXB',
 '5MHS',
 '4J8R',
 '2Y6S',
 '3WKT',
 '6IEC',
 '2WFX',
 '6BXC',
 '3VG9',
 '6F9S',
 '2XQR',
 '5WB7',
 '1DAN',
 '2AK4',
 '3FHC',
 ...]

In [18]:
# exlude pdbs in exclude_list for raw_dimer_db
dimer_db = raw_dimer_db[~raw_dimer_db['PDB'].isin(exclude_list)]
# rename chain_1 and chain_2 to Receptor Chains,Ligand Chains
dimer_db = dimer_db.rename(columns={'chain_1': 'Receptor Chains', 'chain_2': 'Ligand Chains','path':'paths'})
dimer_db['affinity'] = 1.0
# remove source	cluster_rep	cluster_size is_representative
dimer_db = dimer_db.drop(columns=['source', 'cluster_rep', 'cluster_size', 'is_representative'])
# save dimer_db to csv
dimer_db.to_csv("./saved_tables/dimer_table.csv", index=False)
dimer_db

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,1AKH,A,B,../../PDB/new_dimer_db/1AKH.pdb,1.0
1,1B34,A,B,../../PDB/new_dimer_db/1B34.pdb,1.0
2,1BND,A,B,../../PDB/new_dimer_db/1BND.pdb,1.0
3,1CF7,A,B,../../PDB/new_dimer_db/1CF7.pdb,1.0
4,1CI6,A,B,../../PDB/new_dimer_db/1CI6.pdb,1.0
...,...,...,...,...,...
9372,7CD9,A,B,../../PDB/old_dimer_db/7CD9.pdb,1.0
9373,7CKF,A,B,../../PDB/old_dimer_db/7CKF.pdb,1.0
9374,7NBI,A,B,../../PDB/old_dimer_db/7NBI.pdb,1.0
9375,7NDL,A,B,../../PDB/old_dimer_db/7NDL.pdb,1.0
9376,5XSP,A,B,../../PDB/old_dimer_db/5XSP.pdb,1.0

## Check if S90 all in our database

In [ ]:
i=0
for pdb in S90_list:
    if pdb not in all_pdb_list and pdb.upper() not in prem_pdb_list:
        print(pdb)
        i += 1
print(i)

0

## Check if S79 all in our database

In [ ]:
i = 0
for pdb in S79_df['PDB'].tolist():
	if pdb.lower() not in all_pdb_list and pdb.upper() not in prem_pdb_list:
		print(pdb)
		i += 1
print(i)

0

## Check if SKEMPI test all in our database

In [3]:
SKEMPI_test_df = SKEMPI_df.copy(deep=True)
SKEMPI_test_df['PDB'] = [p[:4] for p in SKEMPI_test_df['#Pdb'].tolist()]
SKEMPI_test_df['Mutations'] = None
for ind,row in SKEMPI_test_df.iterrows():
	if pd.notna(row['Mutation(s)_cleaned']):
		new_mut_list = []
		for mut_str in row['Mutation(s)_cleaned'].split('_'):
			chain_id = mut_str[1]
			mut_info = mut_str[0]+mut_str[2:]
			new_mut_list.append(f"{chain_id}_{mut_info}")
		SKEMPI_test_df.at[ind, 'Mutations'] = ', '.join(new_mut_list)
SKEMPI_test_df.drop(columns=['#Pdb', 'Mutation(s)_cleaned','Mutation(s)_PDB'], inplace=True)

In [4]:
SKEMPI_test_df

     Binding_affinity   PDB       Mutations
0               -16.3  1CSE            None
1               -14.0  1CSE          I_L38G
2               -15.1  1CSE          I_L38S
3                -9.5  1CSE          I_L38P
4               -13.3  1CSE          I_L38I
..                ...   ...             ...
161              -7.0  2KSO  A_K49D, B_D36K
162              -7.9  2KSO          A_R43E
163              -8.0  2KSO  A_R43E, B_H20R
164              -6.8  2KSO  A_R43E, B_H20E
165              -7.4  2KSO          B_H20E

[166 rows x 3 columns]

### Check if mutants are in our mutant dataset

In [5]:
# Function to normalize mutations: split by ', ', strip, sort, join
def normalize_mutations(mut_str):
    if pd.isna(mut_str):
        return mut_str
    muts = [m.strip() for m in mut_str.split(', ')]
    return ', '.join(sorted(muts))

# Apply normalization to both dataframes
SKEMPI_test_df['Mutations_norm'] = SKEMPI_test_df['Mutations'].apply(normalize_mutations)
mut_df['Mutations_norm'] = mut_df['Mutations'].apply(normalize_mutations)

# Now merge on 'PDB' and 'Mutations_norm'
common_rows = pd.merge(SKEMPI_test_df[['PDB', 'Mutations_norm']], mut_df[['PDB', 'Mutations_norm','mut_paths']], on=['PDB', 'Mutations_norm'], how='inner')
print("Common rows after normalization:")
print(common_rows)
print(f"Number of common rows: {len(common_rows)}")

# For different rows
diff_rows = pd.merge(SKEMPI_test_df[['PDB', 'Mutations_norm']], mut_df[['PDB', 'Mutations_norm']], on=['PDB', 'Mutations_norm'], how='left', indicator=True)
diff_rows = diff_rows[diff_rows['_merge'] == 'left_only'].drop(columns=['_merge'])
print("Different rows after normalization:")
print(diff_rows[diff_rows['Mutations_norm'].notna()])
print(f"Number of different rows: {len(diff_rows)}")

Common rows after normalization:
      PDB  Mutations_norm                         mut_paths
0    1CSE          I_L38G   PDB/mutant_pdbs/1cse/1cse_1.pdb
1    1CSE          I_L38S   PDB/mutant_pdbs/1cse/1cse_2.pdb
2    1CSE          I_L38P   PDB/mutant_pdbs/1cse/1cse_3.pdb
3    1CSE          I_L38I   PDB/mutant_pdbs/1cse/1cse_4.pdb
4    1CSE          I_L38D   PDB/mutant_pdbs/1cse/1cse_5.pdb
..    ...             ...                               ...
135  2KSO  A_K49D, B_D36K   PDB/mutant_pdbs/2kso/2kso_6.pdb
136  2KSO          A_R43E   PDB/mutant_pdbs/2kso/2kso_7.pdb
137  2KSO  A_R43E, B_H20R   PDB/mutant_pdbs/2kso/2kso_8.pdb
138  2KSO  A_R43E, B_H20E   PDB/mutant_pdbs/2kso/2kso_9.pdb
139  2KSO          B_H20E  PDB/mutant_pdbs/2kso/2kso_10.pdb

[140 rows x 3 columns]
Number of common rows: 140
Different rows after normalization:
Empty DataFrame
Columns: [PDB, Mutations_norm]
Index: []
Number of different rows: 26

In [9]:
common_rows

      PDB  Mutations_norm                         mut_paths
0    1CSE          I_L38G   PDB/mutant_pdbs/1cse/1cse_1.pdb
1    1CSE          I_L38S   PDB/mutant_pdbs/1cse/1cse_2.pdb
2    1CSE          I_L38P   PDB/mutant_pdbs/1cse/1cse_3.pdb
3    1CSE          I_L38I   PDB/mutant_pdbs/1cse/1cse_4.pdb
4    1CSE          I_L38D   PDB/mutant_pdbs/1cse/1cse_5.pdb
..    ...             ...                               ...
135  2KSO  A_K49D, B_D36K   PDB/mutant_pdbs/2kso/2kso_6.pdb
136  2KSO          A_R43E   PDB/mutant_pdbs/2kso/2kso_7.pdb
137  2KSO  A_R43E, B_H20R   PDB/mutant_pdbs/2kso/2kso_8.pdb
138  2KSO  A_R43E, B_H20E   PDB/mutant_pdbs/2kso/2kso_9.pdb
139  2KSO          B_H20E  PDB/mutant_pdbs/2kso/2kso_10.pdb

[140 rows x 3 columns]

### Check if wild type in SKEMPI in our database

In [7]:
wt_pdb_list = SKEMPI_test_df['PDB'].unique().tolist()
print(f"Number of unique PDBs in SKEMPI test set: {len(wt_pdb_list)}")
i = 0
for pdb in wt_pdb_list:
	if pdb.lower() not in all_pdb_list and pdb.upper() not in all_pdb_list:
		print(pdb)
		i += 1
print(i)

Number of unique PDBs in SKEMPI test set: 26
0

## Move test samples out of our database

In [ ]:
for pdb in S90_list:
    # move file at ../../curated_db/unmut_sthg_8A/{pdb}.pkl to ../../curated_db/S90/
    pdb = pdb.lower()
    src_path = f"../../curated_db/unmut_sthg_8A/{pdb}.pkl"
    dest_path = f"../../curated_db/S90/{pdb}.pkl"
    src_path_esm = f"../../curated_db/unmut_sthg_esm_8A/{pdb}.pkl"
    dest_path_esm = f"../../curated_db/S90_esm/{pdb}.pkl"
    if os.path.exists(src_path) and not os.path.exists(dest_path):
        os.system(f"mv {src_path} {dest_path}")
        print(f"Moved {src_path} to {dest_path}")
    if os.path.exists(src_path_esm) and not os.path.exists(dest_path_esm):
        os.system(f"mv {src_path_esm} {dest_path_esm}")
        print(f"Moved {src_path_esm} to {dest_path_esm}")
    src_path_dimer  = f"../../curated_db/dimer_sthg_8A/{pdb}.pkl"
    src_path_dimer_esm  = f"../../curated_db/dimer_sthg_esm_8A/{pdb}.pkl"
    if os.path.exists(src_path_dimer):
        os.system(f"rm {src_path_dimer}")
        print(f"Removed {src_path_dimer}")
    if os.path.exists(src_path_dimer_esm):
        os.system(f"rm {src_path_dimer_esm}")
        print(f"Removed {src_path_dimer_esm}")

File 1an1: source exists: False, destination exists: True
File 1an1 ESM: source exists: False, destination exists: True
File 1axi: source exists: False, destination exists: True
File 1axi ESM: source exists: False, destination exists: True
File 1dpj: source exists: False, destination exists: True
File 1dpj ESM: source exists: False, destination exists: True
File 1ees: source exists: False, destination exists: True
File 1ees ESM: source exists: False, destination exists: True
File 1fle: source exists: False, destination exists: True
File 1fle ESM: source exists: False, destination exists: True
File 1jtd: source exists: False, destination exists: True
File 1jtd ESM: source exists: False, destination exists: True
File 1pjn: source exists: False, destination exists: True
File 1pjn ESM: source exists: False, destination exists: True
File 1sb0: source exists: False, destination exists: True
File 1sb0 ESM: source exists: False, destination exists: True
File 1t63: source exists: False, destination exists: True
File 1t63 ESM: source exists: False, destination exists: True
File 1t6b: source exists: False, destination exists: True
File 1t6b ESM: source exists: False, destination exists: True
File 1tba: source exists: False, destination exists: True
File 1tba ESM: source exists: False, destination exists: True
File 1tm4: source exists: False, destination exists: True
File 1tm4 ESM: source exists: False, destination exists: True
File 1uel: source exists: False, destination exists: True
File 1uel ESM: source exists: False, destination exists: True
File 1veu: source exists: False, destination exists: True
File 1veu ESM: source exists: False, destination exists: True
File 1wa7: source exists: False, destination exists: True
File 1wa7 ESM: source exists: False, destination exists: True
File 1wr1: source exists: False, destination exists: True
File 1wr1 ESM: source exists: False, destination exists: True
File 1zgu: source exists: False, destination exists: True
File 1zgu ESM: source exists: False, destination exists: True
File 2ftl: source exists: False, destination exists: True
File 2ftl ESM: source exists: False, destination exists: True
File 2jgz: source exists: False, destination exists: True
File 2jgz ESM: source exists: False, destination exists: True
File 2jt4: source exists: False, destination exists: True
File 2jt4 ESM: source exists: False, destination exists: True
File 2k5b: source exists: False, destination exists: True
File 2k5b ESM: source exists: False, destination exists: True
File 2k8f: source exists: False, destination exists: True
File 2k8f ESM: source exists: False, destination exists: True
File 2lp4: source exists: False, destination exists: True
File 2lp4 ESM: source exists: False, destination exists: True
File 2luh: source exists: False, destination exists: True
File 2luh ESM: source exists: False, destination exists: True
File 2n73: source exists: False, destination exists: True
File 2n73 ESM: source exists: False, destination exists: True
File 2n8j: source exists: False, destination exists: True
File 2n8j ESM: source exists: False, destination exists: True
File 2o3b: source exists: False, destination exists: True
File 2o3b ESM: source exists: False, destination exists: True
File 2o8v: source exists: False, destination exists: True
File 2o8v ESM: source exists: False, destination exists: True
File 2omu: source exists: False, destination exists: True
File 2omu ESM: source exists: False, destination exists: True
File 2p44: source exists: False, destination exists: True
File 2p44 ESM: source exists: False, destination exists: True
File 2rnr: source exists: False, destination exists: True
File 2rnr ESM: source exists: False, destination exists: True
File 2vda: source exists: False, destination exists: True
File 2vda ESM: source exists: False, destination exists: True
File 2wwx: source exists: False, destination exists: True
File 2wwx ESM: source exists: False, destination exists: True
File 2xtt: source exists: False, destination exists: True
File 2xtt ESM: source exists: False, destination exists: True
File 3bh6: source exists: False, destination exists: True
File 3bh6 ESM: source exists: False, destination exists: True
File 3ch5: source exists: False, destination exists: True
File 3ch5 ESM: source exists: False, destination exists: True
File 3di3: source exists: False, destination exists: True
File 3di3 ESM: source exists: False, destination exists: True
File 3gj3: source exists: False, destination exists: True
File 3gj3 ESM: source exists: False, destination exists: True
File 3h6g: source exists: False, destination exists: True
File 3h6g ESM: source exists: False, destination exists: True
File 3knb: source exists: False, destination exists: True
File 3knb ESM: source exists: False, destination exists: True
File 3kud: source exists: False, destination exists: True
File 3kud ESM: source exists: False, destination exists: True
File 3kw5: source exists: False, destination exists: True
File 3kw5 ESM: source exists: False, destination exists: True
File 3n4i: source exists: False, destination exists: True
File 3n4i ESM: source exists: False, destination exists: True
File 3oky: source exists: False, destination exists: True
File 3oky ESM: source exists: False, destination exists: True
File 3ona: source exists: False, destination exists: True
File 3ona ESM: source exists: False, destination exists: True
File 3uyp: source exists: False, destination exists: True
File 3uyp ESM: source exists: False, destination exists: True
File 3vv2: source exists: False, destination exists: True
File 3vv2 ESM: source exists: False, destination exists: True
File 4apx: source exists: False, destination exists: True
File 4apx ESM: source exists: False, destination exists: True
File 4d0g: source exists: False, destination exists: True
File 4d0g ESM: source exists: False, destination exists: True
File 4exp: source exists: False, destination exists: True
File 4exp ESM: source exists: False, destination exists: True
File 4f48: source exists: False, destination exists: True
File 4f48 ESM: source exists: False, destination exists: True
File 4i6l: source exists: False, destination exists: True
File 4i6l ESM: source exists: False, destination exists: True
File 4iyp: source exists: False, destination exists: True
File 4iyp ESM: source exists: False, destination exists: True
File 4je4: source exists: False, destination exists: True
File 4je4 ESM: source exists: False, destination exists: True
File 4p3y: source exists: False, destination exists: True
File 4p3y ESM: source exists: False, destination exists: True
File 4rey: source exists: False, destination exists: True
File 4rey ESM: source exists: False, destination exists: True
File 4rt6: source exists: False, destination exists: True
File 4rt6 ESM: source exists: False, destination exists: True
Removed ../../curated_db/capri_sthg_8A/4rt6.pkl
Removed ../../curated_db/capri_sthg_esm_8A/4rt6.pkl
File 4uyq: source exists: False, destination exists: True
File 4uyq ESM: source exists: False, destination exists: True
File 4wnd: source exists: False, destination exists: True
File 4wnd ESM: source exists: False, destination exists: True
File 4x33: source exists: False, destination exists: True
File 4x33 ESM: source exists: False, destination exists: True
File 4zqu: source exists: False, destination exists: True
File 4zqu ESM: source exists: False, destination exists: True
File 5eql: source exists: False, destination exists: True
File 5eql ESM: source exists: False, destination exists: True
File 5f4e: source exists: False, destination exists: True
File 5f4e ESM: source exists: False, destination exists: True
File 5g1x: source exists: False, destination exists: True
File 5g1x ESM: source exists: False, destination exists: True
File 5k22: source exists: False, destination exists: True
File 5k22 ESM: source exists: False, destination exists: True
File 5l8j: source exists: False, destination exists: True
File 5l8j ESM: source exists: False, destination exists: True
File 5ml9: source exists: False, destination exists: True
File 5ml9 ESM: source exists: False, destination exists: True
File 5mtm: source exists: False, destination exists: True
File 5mtm ESM: source exists: False, destination exists: True
File 5nwm: source exists: False, destination exists: True
File 5nwm ESM: source exists: False, destination exists: True
File 5szj: source exists: False, destination exists: True
File 5szj ESM: source exists: False, destination exists: True
File 5szk: source exists: False, destination exists: True
File 5szk ESM: source exists: False, destination exists: True
File 5tvq: source exists: False, destination exists: True
File 5tvq ESM: source exists: False, destination exists: True
File 5ufe: source exists: False, destination exists: True
File 5ufe ESM: source exists: False, destination exists: True
File 5v6a: source exists: False, destination exists: True
File 5v6a ESM: source exists: False, destination exists: True
File 5wpa: source exists: False, destination exists: True
File 5wpa ESM: source exists: False, destination exists: True
File 5xoc: source exists: False, destination exists: True
File 5xoc ESM: source exists: False, destination exists: True
File 5yr0: source exists: False, destination exists: True
File 5yr0 ESM: source exists: False, destination exists: True
File 6arq: source exists: False, destination exists: True
File 6arq ESM: source exists: False, destination exists: True
File 6aw2: source exists: False, destination exists: True
File 6aw2 ESM: source exists: False, destination exists: True
File 6cbp: source exists: False, destination exists: True
File 6cbp ESM: source exists: False, destination exists: True
File 6d13: source exists: False, destination exists: True
File 6d13 ESM: source exists: False, destination exists: True
File 6e3i: source exists: False, destination exists: True
File 6e3i ESM: source exists: False, destination exists: True
File 6eg0: source exists: False, destination exists: True
File 6eg0 ESM: source exists: False, destination exists: True
File 6f9s: source exists: False, destination exists: True
File 6f9s ESM: source exists: False, destination exists: True
File 6ff3: source exists: False, destination exists: True
File 6ff3 ESM: source exists: False, destination exists: True
File 6fg8: source exists: False, destination exists: True
File 6fg8 ESM: source exists: False, destination exists: True
File 6fud: source exists: False, destination exists: True
File 6fud ESM: source exists: False, destination exists: True
File 6gbg: source exists: False, destination exists: True
File 6gbg ESM: source exists: False, destination exists: True
Removed ../../curated_db/capri_sthg_8A/6gbg.pkl
Removed ../../curated_db/capri_sthg_esm_8A/6gbg.pkl
File 6i3f: source exists: False, destination exists: True
File 6i3f ESM: source exists: False, destination exists: True
File 6isc: source exists: False, destination exists: True
File 6isc ESM: source exists: False, destination exists: True

In [ ]:
for pdb in S79_df['PDB'].tolist():
    pdb = pdb.lower()
    src_path = f"../../curated_db/unmut_sthg_8A/{pdb}.pkl"
    dest_path = f"../../curated_db/S79/{pdb}.pkl"
    src_path_esm = f"../../curated_db/unmut_sthg_esm_8A/{pdb}.pkl"
    dest_path_esm = f"../../curated_db/S79_esm/{pdb}.pkl"
    if os.path.exists(src_path) and not os.path.exists(dest_path):
        os.system(f"mv {src_path} {dest_path}")
        print(f"Moved {src_path} to {dest_path}")

    if os.path.exists(src_path_esm) and not os.path.exists(dest_path_esm):
        os.system(f"mv {src_path_esm} {dest_path_esm}")
        print(f"Moved {src_path_esm} to {dest_path_esm}")
    src_path_dimer_esm  = f"../../curated_db/dimer_sthg_esm_8A/{pdb}.pkl"
    if os.path.exists(src_path_dimer):
        os.system(f"rm {src_path_dimer}")
        print(f"Removed {src_path_dimer}")
    if os.path.exists(src_path_dimer_esm):
        os.system(f"rm {src_path_dimer_esm}")
        print(f"Removed {src_path_dimer_esm}")
    src_path_capri = f"../../curated_db/capri_sthg_8A/{pdb}.pkl"
    src_path_capri_esm = f"../../curated_db/capri_sthg_esm_8A/{pdb}.pkl"
    if os.path.exists(src_path_capri):
        os.system(f"rm {src_path_capri}")
        print(f"Removed {src_path_capri}")
    if os.path.exists(src_path_capri_esm):
        os.system(f"rm {src_path_capri_esm}")
        print(f"Removed {src_path_capri_esm}")

File 1wej: source exists: False, destination exists: True
File 1wej ESM: source exists: False, destination exists: True
File 1ppe: source exists: False, destination exists: True
File 1ppe ESM: source exists: False, destination exists: True
File 1pvh: source exists: False, destination exists: True
File 1pvh ESM: source exists: False, destination exists: True
File 3sgb: source exists: False, destination exists: True
File 3sgb ESM: source exists: False, destination exists: True
File 1ktz: source exists: False, destination exists: True
File 1ktz ESM: source exists: False, destination exists: True
File 2pcc: source exists: False, destination exists: True
File 2pcc ESM: source exists: False, destination exists: True
File 2mta: source exists: False, destination exists: True
File 2mta ESM: source exists: False, destination exists: True
File 1fsk: source exists: False, destination exists: True
File 1fsk ESM: source exists: False, destination exists: True
File 1r0r: source exists: False, destination exists: True
File 1r0r ESM: source exists: False, destination exists: True
File 2pcb: source exists: False, destination exists: True
File 2pcb ESM: source exists: False, destination exists: True
File 1p2c: source exists: False, destination exists: True
File 1p2c ESM: source exists: False, destination exists: True
File 1jtg: source exists: False, destination exists: True
File 1jtg ESM: source exists: False, destination exists: True
File 1bj1: source exists: False, destination exists: True
File 1bj1 ESM: source exists: False, destination exists: True
File 1jps: source exists: False, destination exists: True
File 1jps ESM: source exists: False, destination exists: True
File 1z0k: source exists: False, destination exists: True
File 1z0k ESM: source exists: False, destination exists: True
File 2tgp: source exists: False, destination exists: True
File 2tgp ESM: source exists: False, destination exists: True
File 1mlc: source exists: False, destination exists: True
File 1mlc ESM: source exists: False, destination exists: True
File 2gox: source exists: False, destination exists: True
File 2gox ESM: source exists: False, destination exists: True
File 1j2j: source exists: False, destination exists: True
File 1j2j ESM: source exists: False, destination exists: True
File 2ajf: source exists: False, destination exists: True
File 2ajf ESM: source exists: False, destination exists: True
File 1zhi: source exists: False, destination exists: True
File 1zhi ESM: source exists: False, destination exists: True
File 1e96: source exists: False, destination exists: True
File 1e96 ESM: source exists: False, destination exists: True
File 1kxq: source exists: False, destination exists: True
File 1kxq ESM: source exists: False, destination exists: True
File 1avz: source exists: False, destination exists: True
File 1avz ESM: source exists: False, destination exists: True
File 1qa9: source exists: False, destination exists: True
File 1qa9 ESM: source exists: False, destination exists: True
File 1cbw: source exists: False, destination exists: True
File 1cbw ESM: source exists: False, destination exists: True
File 1buh: source exists: False, destination exists: True
File 1buh ESM: source exists: False, destination exists: True
File 1dqj: source exists: False, destination exists: True
File 1dqj ESM: source exists: False, destination exists: True
File 1ewy: source exists: False, destination exists: True
File 1ewy ESM: source exists: False, destination exists: True
File 2vir: source exists: False, destination exists: True
File 2vir ESM: source exists: False, destination exists: True
File 2vis: source exists: False, destination exists: True
File 2vis ESM: source exists: False, destination exists: True
File 2a9k: source exists: False, destination exists: True
File 2a9k ESM: source exists: False, destination exists: True
File 2oob: source exists: False, destination exists: True
File 2oob ESM: source exists: False, destination exists: True
File 1bvn: source exists: False, destination exists: True
File 1bvn ESM: source exists: False, destination exists: True
File 1efn: source exists: False, destination exists: True
File 1efn ESM: source exists: False, destination exists: True
File 2abz: source exists: False, destination exists: True
File 2abz ESM: source exists: False, destination exists: True
File 1gcq: source exists: False, destination exists: True
File 1gcq ESM: source exists: False, destination exists: True
File 1he8: source exists: False, destination exists: True
File 1he8 ESM: source exists: False, destination exists: True
File 1kac: source exists: False, destination exists: True
File 1kac ESM: source exists: False, destination exists: True
File 1gla: source exists: False, destination exists: True
File 1gla ESM: source exists: False, destination exists: True
File 1s1q: source exists: False, destination exists: True
File 1s1q ESM: source exists: False, destination exists: True
File 1vfb: source exists: False, destination exists: True
File 1vfb ESM: source exists: False, destination exists: True
File 2fju: source exists: False, destination exists: True
File 2fju ESM: source exists: False, destination exists: True
File 1e6j: source exists: False, destination exists: True
File 1e6j ESM: source exists: False, destination exists: True
File 1us7: source exists: False, destination exists: True
File 1us7 ESM: source exists: False, destination exists: True
File 1acb: source exists: False, destination exists: True
File 1acb ESM: source exists: False, destination exists: True
File 3bzd: source exists: False, destination exists: True
File 3bzd ESM: source exists: False, destination exists: True
File 1a2k: source exists: False, destination exists: True
File 1a2k ESM: source exists: False, destination exists: True
File 1akj: source exists: False, destination exists: True
File 1akj ESM: source exists: False, destination exists: True
File 2hqs: source exists: False, destination exists: True
File 2hqs ESM: source exists: False, destination exists: True
Removed ../../curated_db/capri_sthg_8A/2hqs.pkl
Removed ../../curated_db/capri_sthg_esm_8A/2hqs.pkl
File 1k5d: source exists: False, destination exists: True
File 1k5d ESM: source exists: False, destination exists: True
File 1ezu: source exists: False, destination exists: True
File 1ezu ESM: source exists: False, destination exists: True
File 2i25: source exists: False, destination exists: True
File 2i25 ESM: source exists: False, destination exists: True
File 1bvk: source exists: False, destination exists: True
File 1bvk ESM: source exists: False, destination exists: True
File 1jwh: source exists: False, destination exists: True
File 1jwh ESM: source exists: False, destination exists: True
File 1emv: source exists: False, destination exists: True
File 1emv ESM: source exists: False, destination exists: True
File 1xu1: source exists: False, destination exists: True
File 1xu1 ESM: source exists: False, destination exists: True
File 1ak4: source exists: False, destination exists: True
File 1ak4 ESM: source exists: False, destination exists: True
File 1e6e: source exists: False, destination exists: True
File 1e6e ESM: source exists: False, destination exists: True
File 1gxd: source exists: False, destination exists: True
File 1gxd ESM: source exists: False, destination exists: True
File 1i4d: source exists: False, destination exists: True
File 1i4d ESM: source exists: False, destination exists: True
File 1ffw: source exists: False, destination exists: True
File 1ffw ESM: source exists: False, destination exists: True
File 4cpa: source exists: False, destination exists: True
File 4cpa ESM: source exists: False, destination exists: True
File 2wpt: source exists: False, destination exists: True
File 2wpt ESM: source exists: False, destination exists: True
Removed ../../curated_db/capri_sthg_8A/2wpt.pkl
Removed ../../curated_db/capri_sthg_esm_8A/2wpt.pkl
File 1fc2: source exists: False, destination exists: True
File 1fc2 ESM: source exists: False, destination exists: True
File 1mq8: source exists: False, destination exists: True
File 1mq8 ESM: source exists: False, destination exists: True
File 1xqs: source exists: False, destination exists: True
File 1xqs ESM: source exists: False, destination exists: True
File 1lfd: source exists: False, destination exists: True
File 1lfd ESM: source exists: False, destination exists: True
File 2aq3: source exists: False, destination exists: True
File 2aq3 ESM: source exists: False, destination exists: True
File 1b6c: source exists: False, destination exists: True
File 1b6c ESM: source exists: False, destination exists: True
File 2hrk: source exists: False, destination exists: True
File 2hrk ESM: source exists: False, destination exists: True
File 2nyz: source exists: False, destination exists: True
File 2nyz ESM: source exists: False, destination exists: True
File 1i2m: source exists: False, destination exists: True
File 1i2m ESM: source exists: False, destination exists: True
File 3cph: source exists: False, destination exists: True
File 3cph ESM: source exists: False, destination exists: True
File 1kkl: source exists: False, destination exists: True
File 1kkl ESM: source exists: False, destination exists: True
File 1eer: source exists: False, destination exists: True
File 1eer ESM: source exists: False, destination exists: True
File 1e4k: source exists: False, destination exists: True
File 1e4k ESM: source exists: False, destination exists: True
File 2c0l: source exists: False, destination exists: True
File 2c0l ESM: source exists: False, destination exists: True
File 1atn: source exists: False, destination exists: True
File 1atn ESM: source exists: False, destination exists: True

In [ ]:
for pdb in diff_rows['PDB'].tolist():
    pdb = pdb.lower()
    src_path = f"../../curated_db/unmut_sthg_8A/{pdb}.pkl"
    dest_path = f"../../curated_db/SKEMPI_test_new/{pdb}.pkl"
    src_path_esm = f"../../curated_db/unmut_sthg_esm_8A/{pdb}.pkl"
    dest_path_esm = f"../../curated_db/SKEMPI_test_esm_new/{pdb}.pkl"
    if os.path.exists(src_path) and not os.path.exists(dest_path):
        os.system(f"mv {src_path} {dest_path}")
        print(f"Moved {src_path} to {dest_path}")
    #else:
    #    print(f"File {pdb}: source exists: {os.path.exists(src_path)}, destination exists: {os.path.exists(dest_path)}")
    if os.path.exists(src_path_esm) and not os.path.exists(dest_path_esm):
        os.system(f"mv {src_path_esm} {dest_path_esm}")
        print(f"Moved {src_path_esm} to {dest_path_esm}")

    src_path_dimer  = f"../../curated_db/dimer_sthg_8A/{pdb}.pkl"
    src_path_dimer_esm  = f"../../curated_db/dimer_sthg_esm_8A/{pdb}.pkl"
    if os.path.exists(src_path_dimer):
        os.system(f"rm {src_path_dimer}")
        print(f"Removed {src_path_dimer}")
    if os.path.exists(src_path_dimer_esm):
        os.system(f"rm {src_path_dimer_esm}")
        print(f"Removed {src_path_dimer_esm}")
    src_path_capri = f"../../curated_db/capri_sthg_8A/{pdb}.pkl"
    src_path_capri_esm = f"../../curated_db/capri_sthg_esm_8A/{pdb}.pkl"
    if os.path.exists(src_path_capri):
        os.system(f"rm {src_path_capri}")
        print(f"Removed {src_path_capri}")
    if os.path.exists(src_path_capri_esm):
        os.system(f"rm {src_path_capri_esm}")
        print(f"Removed {src_path_capri_esm}")

Removed ../../curated_db/dimer_sthg_8A/1iar.pkl
Removed ../../curated_db/dimer_sthg_esm_8A/1iar.pkl
Removed ../../curated_db/dimer_sthg_esm480_8A/1iar.pkl
Removed ../../curated_db/dimer_sthg_8A/4yfd.pkl
Removed ../../curated_db/dimer_sthg_esm_8A/4yfd.pkl
Removed ../../curated_db/dimer_sthg_esm480_8A/4yfd.pkl
Removed ../../curated_db/dimer_sthg_8A/1k8r.pkl
Removed ../../curated_db/dimer_sthg_esm_8A/1k8r.pkl
Removed ../../curated_db/dimer_sthg_esm480_8A/1k8r.pkl
Removed ../../curated_db/dimer_sthg_8A/5k39.pkl
Removed ../../curated_db/dimer_sthg_esm_8A/5k39.pkl
Removed ../../curated_db/dimer_sthg_esm480_8A/5k39.pkl
Removed ../../curated_db/dimer_sthg_8A/5m2o.pkl
Removed ../../curated_db/dimer_sthg_esm_8A/5m2o.pkl
Removed ../../curated_db/dimer_sthg_esm480_8A/5m2o.pkl

In [ ]:
root_path = "../../GraPPI_data/curated_db/mutant_sthg_8A_new/"
root_path_esm = "../../GraPPI_data/curated_db/mutant_sthg_esm_8A_new/"

for mut_pdb_path in common_rows['mut_paths'].tolist():
    mut_pdb = os.path.basename(mut_pdb_path).split('.')[0]
    if mut_pdb.lower() in [f.split('.')[0] for f in os.listdir(root_path)]:
        os.system(f"mv {root_path}{mut_pdb}.pkl ../../curated_db/SKEMPI_test_new/{mut_pdb}.pkl")
    elif not os.path.exists(f"../../curated_db/SKEMPI_test/{mut_pdb.lower()}.pkl"):
        print(f"No file in SKEMPI_test for mutant PDB: {mut_pdb}")
    else:
        print(f"Cannot find mutant PDB file: {mut_pdb} in {root_path}")
    if mut_pdb.lower() in [f.split('.')[0] for f in os.listdir(root_path_esm)]:
        os.system(f"mv {root_path_esm}{mut_pdb}.pkl ../../curated_db/SKEMPI_test_esm_new/{mut_pdb}.pkl")
    elif not os.path.exists(f"../../curated_db/SKEMPI_test_esm/{mut_pdb.lower()}.pkl"):
        print(f"No file in SKEMPI_test_esm for mutant PDB: {mut_pdb}")
    else:
        print(f"Cannot find mutant PDB file: {mut_pdb} in {root_path_esm}")

# Split internal testset

In [23]:
import sys
sys.path.append("..")
from utils.Training_modules.common_utils import (
    load_sttgs_from_dir, filter_samples_finetune,get_sample_type,
    stratified_train_test_split, save_split_info
)
from collections import defaultdict

In [ ]:
pdb_dir = "../../GraPPI_data/curated_db/all_sthg_esm_8A/"
all_sttgs = load_sttgs_from_dir(pdb_dir)
all_sttgs = filter_samples_finetune(all_sttgs, min_nodes=5)
# Convert to samples
all_samples = []
for name, st in all_sttgs.items():
	graph = st.protein_graph
	affinity = graph.y.item() if hasattr(graph.y, 'item') else graph.y
	sample_type = get_sample_type(affinity, 1.1)
	all_samples.append((name, graph, affinity, sample_type))
# Count sample types
type_counts = defaultdict(int)
for s in all_samples:
	type_counts[s[3]] += 1

print(f"\nTotal samples: {len(all_samples)}")
print(f"Premium: {type_counts['premium']}, Golden: {type_counts['golden']}, Negative: {type_counts['negative']}")

if len(all_samples) == 0:
	raise ValueError("No samples loaded.")

PDB graphs loading: 100%|██████████| 14123/14123 [02:03<00:00, 114.43it/s]

Total samples: 14099
Premium: 2895, Golden: 4976, Negative: 6228

In [25]:
train_samples, test_samples = stratified_train_test_split(
	all_samples,
	test_ratio=0.2,
	seed=42
)

In [26]:
final_save_dir = "./"
save_split_info(train_samples, test_samples, final_save_dir, prefix="internal_test")

Split info saved to: ./internal_test_split_info.json

'./internal_test_split_info.json'

# Load saved test set pdb list

In [ ]:
with open('./simple_test_split_info.json', 'r') as f:
    train_test_set = json.load(f)
test_set = train_test_set['test_by_type']['premium']

In [3]:
len(test_set)

611

In [26]:
train_test_set.keys()

dict_keys(['train_samples', 'test_samples', 'train_count', 'test_count', 'train_by_type', 'test_by_type'])

# Load dataframe that contains PDB affinity

In [4]:
df = pd.read_csv('./saved_tables/wt_table.csv')

In [5]:
df

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,1A22,B,A,../../PDB/SKEMPI_v2.0/1A22.pdb,12.622671
1,1A4Y,B,A,../../PDB/SKEMPI_v2.0/1A4Y.pdb,20.658646
2,1ACB,I,E,../../PDB/SKEMPI_v2.0/1ACB.pdb,14.567624
3,1AHW,C,"A, B",../../PDB/SKEMPI_v2.0/1AHW.pdb,11.547342
4,1AK4,D,A,../../PDB/SKEMPI_v2.0/1AK4.pdb,6.606704
...,...,...,...,...,...
3093,5E94,"A, B",G,../../PDB/updated_pdb/5E94.pdb,11.621462
3094,5EIV,"A, G, H","I, J, K",../../PDB/updated_pdb/5EIV.pdb,6.203861
3095,5IBK,"A, B",C,../../PDB/updated_pdb/5IBK.pdb,9.756143
3096,6GWC,"A, B",C,../../PDB/updated_pdb/6GWC.pdb,8.956734
3097,6S53,"B, F",E,../../PDB/updated_pdb/6S53.pdb,7.228276

# Extract dataframes that only for test PDBs

In [6]:
df_test = df[
    df['PDB'].astype(str).str.casefold().isin({str(x).casefold() for x in test_set})
].reset_index(drop=True)

In [7]:
df_test

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,1AHW,C,"A, B",../../PDB/SKEMPI_v2.0/1AHW.pdb,11.547342
1,1CSE,I,E,../../PDB/SKEMPI_v2.0/1CSE.pdb,16.076883
2,1CT4,I,E,../../PDB/SKEMPI_v2.0/1CT4.pdb,11.465469
3,1DQJ,C,"A, B",../../PDB/SKEMPI_v2.0/1DQJ.pdb,11.666564
4,1EMV,B,A,../../PDB/SKEMPI_v2.0/1EMV.pdb,18.653317
...,...,...,...,...,...
606,5GPG,A,B,../../PDB/updated_pdb/5GPG.pdb,11.703931
607,3SSB,"I, C",A,../../PDB/updated_pdb/3SSB.pdb,12.574550
608,4KVN,"L, H",A,../../PDB/updated_pdb/4KVN.pdb,11.621462
609,4V3K,"F, D",E,../../PDB/updated_pdb/4V3K.pdb,8.230741
610,5EIV,"A, G, H","I, J, K",../../PDB/updated_pdb/5EIV.pdb,6.203861

In [8]:
testset = {}
for pdb in test_set:
    row = df[df['PDB'].str.lower() == pdb.lower()]
    lc = row['Ligand Chains'].values[0]
    rc = row['Receptor Chains'].values[0]
    ba = row['affinity'].values[0]
    testset[pdb.lower()] = {'chains': ''.join(chain.strip() for chain in lc.split(','))+','+''.join(chain.strip() for chain in rc.split(',')), 'affinity': ba}

In [9]:
testset

{'4lu5': {'chains': 'IM,A', 'affinity': np.float64(13.88256729305642)},
 '3lqa': {'chains': 'HL,CG', 'affinity': np.float64(7.907012001566365)},
 '4p9h': {'chains': 'HL,CG', 'affinity': np.float64(10.199668255271332)},
 '4c4p': {'chains': 'B,A', 'affinity': np.float64(9.002309259320754)},
 '5c07': {'chains': 'ABC,DE', 'affinity': np.float64(6.996113767152314)},
 '5wux': {'chains': 'CD,G', 'affinity': np.float64(14.402267781946003)},
 '5jke': {'chains': 'B,A', 'affinity': np.float64(9.60077414498812)},
 '2a78': {'chains': 'B,A', 'affinity': np.float64(9.847428825772957)},
 '4kvn': {'chains': 'A,LH', 'affinity': np.float64(11.621462141435702)},
 '1p0s': {'chains': 'E,HL', 'affinity': np.float64(14.94272579001768)},
 '5c0b': {'chains': 'ABC,DE', 'affinity': np.float64(8.591836600656825)},
 '4gko': {'chains': 'GH,AB', 'affinity': np.float64(3.850570858106734)},
 '1f7z': {'chains': 'I,A', 'affinity': np.float64(6.690417150596326)},
 '5edv': {'chains': 'CEG,A', 'affinity': np.float64(7.903033964335996)},
 '3dgc': {'chains': 'L,R', 'affinity': np.float64(12.272045912989345)},
 '4jfx': {'chains': 'HL,P', 'affinity': np.float64(8.786372395555384)},
 '2jgz': {'chains': 'B,A', 'affinity': np.float64(4.090681970996448)},
 '5nvk': {'chains': 'B,A', 'affinity': np.float64(12.8146612526603)},
 '5imy': {'chains': 'CD,AB', 'affinity': np.float64(8.329259197468655)},
 '6plk': {'chains': 'E,HL', 'affinity': np.float64(12.189280725918362)},
 '6b0g': {'chains': 'CD,E', 'affinity': np.float64(10.238483781921817)},
 '6gvk': {'chains': 'B,A', 'affinity': np.float64(7.770891283328966)},
 '2pon': {'chains': 'A,B', 'affinity': np.float64(7.982109501657531)},
 '4mqv': {'chains': 'B,A', 'affinity': np.float64(7.550856224182858)},
 '4hcp': {'chains': 'B,A', 'affinity': np.float64(6.854445086594643)},
 '3h42': {'chains': 'HL,AB', 'affinity': np.float64(15.549605611574032)},
 '2b0z': {'chains': 'A,B', 'affinity': np.float64(5.454242627995263)},
 '3he7': {'chains': 'A,CD', 'affinity': np.float64(8.902289763822088)},
 '1s0w': {'chains': 'A,C', 'affinity': np.float64(9.24479386985306)},
 '1sq0': {'chains': 'A,B', 'affinity': np.float64(10.257901484436886)},
 '3p11': {'chains': 'HL,A', 'affinity': np.float64(12.512554928773232)},
 '6fq0': {'chains': 'B,A', 'affinity': np.float64(9.26659462133481)},
 '6bb4': {'chains': 'IM,Q', 'affinity': np.float64(10.652789378685869)},
 '2ccl': {'chains': 'A,B', 'affinity': np.float64(12.132470468392304)},
 '6asr': {'chains': 'B,AC', 'affinity': np.float64(6.581653303054666)},
 '5vwx': {'chains': 'BD,AC', 'affinity': np.float64(10.672335274051116)},
 '2z3q': {'chains': 'A,B', 'affinity': np.float64(14.20859712506702)},
 '5wt9': {'chains': 'HL,G', 'affinity': np.float64(12.052010853843235)},
 '3noc': {'chains': 'DE,ABC', 'affinity': np.float64(12.03193480009963)},
 '2lpb': {'chains': 'B,A', 'affinity': np.float64(6.811910829719881)},
 '6gvl': {'chains': 'B,A', 'affinity': np.float64(5.940416530696927)},
 '3tei': {'chains': 'B,A', 'affinity': np.float64(8.591836600656825)},
 '5t6p': {'chains': 'CD,E', 'affinity': np.float64(8.25706518603063)},
 '4y61': {'chains': 'A,B', 'affinity': np.float64(8.792989077453822)},
 '1j7d': {'chains': 'A,B', 'affinity': np.float64(7.770891283328966)},
 '4apf': {'chains': 'B,A', 'affinity': np.float64(8.436467928324666)},
 '3uzv': {'chains': 'Bb,A', 'affinity': np.float64(12.771833906510032)},
 '5uul': {'chains': 'B,A', 'affinity': np.float64(11.3431321637788)},
 '2ajf': {'chains': 'A,E', 'affinity': np.float64(10.765642040550096)},
 '3e2k': {'chains': 'D,A', 'affinity': np.float64(13.855345609698425)},
 '3ssb': {'chains': 'A,IC', 'affinity': np.float64(12.574550139770588)},
 '3ixs': {'chains': 'B,A', 'affinity': np.float64(9.607317712883242)},
 '5odw': {'chains': 'C,A', 'affinity': np.float64(13.117165479441544)},
 '4f38': {'chains': 'B,A', 'affinity': np.float64(11.641538195179306)},
 '6a79': {'chains': 'LM,B', 'affinity': np.float64(11.026005296058385)},
 '4d9r': {'chains': 'HL,A', 'affinity': np.float64(15.541782566657933)},
 '4asw': {'chains': 'C,AB', 'affinity': np.float64(9.544924598991711)},
 '4ypg': {'chains': 'HL,D', 'affinity': np.float64(14.121780472689824)},
 '3d5o': {'chains': 'F,ABCDE', 'affinity': np.float64(8.181363941992895)},
 '2f4m': {'chains': 'B,A', 'affinity': np.float64(9.800028585323483)},
 '4b1y': {'chains': 'M,B', 'affinity': np.float64(8.9567339413296)},
 '6gbh': {'chains': 'B,A', 'affinity': np.float64(9.764663638701975)},
 '4iz7': {'chains': 'A,B', 'affinity': np.float64(9.438971853084816)},
 '6gtq': {'chains': 'CD,AB', 'affinity': np.float64(8.774968169435196)},
 '5dfv': {'chains': 'CD,A', 'affinity': np.float64(12.682518571653272)},
 '2fjh': {'chains': 'AB,W', 'affinity': np.float64(11.94959638524554)},
 '1jrh': {'chains': 'HL,I', 'affinity': np.float64(10.700830861070305)},
 '5jtm': {'chains': 'EFGH,ABCD', 'affinity': np.float64(6.577692172104367)},
 '4nso': {'chains': 'B,A', 'affinity': np.float64(12.284009690982543)},
 '6jhw': {'chains': 'BD,AC', 'affinity': np.float64(10.560405711218127)},
 '5ufe': {'chains': 'A,B', 'affinity': np.float64(9.951854753358331)},
 '6o3b': {'chains': 'H,EG', 'affinity': np.float64(11.381351028545987)},
 '1an1': {'chains': 'I,E', 'affinity': np.float64(12.334439026880876)},
 '3mac': {'chains': 'HL,A', 'affinity': np.float64(9.182729664509043)},
 '2vn5': {'chains': 'A,B', 'affinity': np.float64(12.683859534230596)},
 '3vwj': {'chains': 'AB,CD', 'affinity': np.float64(8.359674424151132)},
 '5eoc': {'chains': 'JM,Q', 'affinity': np.float64(10.252009029162688)},
 '1o95': {'chains': 'CDEF,AB', 'affinity': np.float64(7.228275943658009)},
 '6fg2': {'chains': 'IM,DE', 'affinity': np.float64(14.94272579001768)},
 '2y36': {'chains': 'HL,P', 'affinity': np.float64(8.754354497071757)},
 '2xqb': {'chains': 'HL,A', 'affinity': np.float64(14.02285323732696)},
 '4p1n': {'chains': 'CD,AB', 'affinity': np.float64(8.786372395555384)},
 '6ii4': {'chains': 'HL,A', 'affinity': np.float64(10.608354526851876)},
 '5kxh': {'chains': 'B,A', 'affinity': np.float64(8.603800378650023)},
 '4cmh': {'chains': 'BC,A', 'affinity': np.float64(13.22513391132423)},
 '5j13': {'chains': 'BC,A', 'affinity': np.float64(13.938110796769402)},
 '3dxa': {'chains': 'AC,DE', 'affinity': np.float64(8.898817844633086)},
 '5o4e': {'chains': 'EF,ABCD', 'affinity': np.float64(11.466093469103544)},
 '5wvo': {'chains': 'C,ABD', 'affinity': np.float64(10.567022393116568)},
 '5f5o': {'chains': 'B,A', 'affinity': np.float64(9.259238168110844)},
 '4wwk': {'chains': 'CD,AB', 'affinity': np.float64(7.360418624665037)},
 '1nb5': {'chains': 'AP,I', 'affinity': np.float64(13.905327141679717)},
 '5b76': {'chains': 'B,A', 'affinity': np.float64(7.1403835655189285)},
 '2ny7': {'chains': 'HL,G', 'affinity': np.float64(10.143389484659076)},
 '1zr0': {'chains': 'B,A', 'affinity': np.float64(10.75311658365837)},
 '1tlh': {'chains': 'B,A', 'affinity': np.float64(4.803658856441621)},
 '4ftv': {'chains': 'ABC,DE', 'affinity': np.float64(7.810691422384374)},
 '5l2k': {'chains': 'AB,DE', 'affinity': np.float64(8.098598754921916)},
 '5vt9': {'chains': 'CD,AB', 'affinity': np.float64(10.908485255990527)},
 '4per': {'chains': 'A,B', 'affinity': np.float64(20.45340985498224)},
 '2bp7': {'chains': 'AC,BD', 'affinity': np.float64(12.272045912989345)},
 '2b12': {'chains': 'A,B', 'affinity': np.float64(6.40733062633015)},
 '1te1': {'chains': 'B,A', 'affinity': np.float64(11.547342171686186)},
 '5lxq': {'chains': 'A,B', 'affinity': np.float64(8.445649304006954)},
 '3eab': {'chains': 'A,G', 'affinity': np.float64(6.709834853111396)},
 '1e4k': {'chains': 'AB,C', 'affinity': np.float64(7.89551261715167)},
 '1cn4': {'chains': 'C,AB', 'affinity': np.float64(8.181363941992895)},
 '2ra3': {'chains': 'CI,AB', 'affinity': np.float64(14.588694568323046)},
 '5omn': {'chains': 'C,B', 'affinity': np.float64(10.938860471398431)},
 '5hlz': {'chains': 'BD,AC', 'affinity': np.float64(11.318957914654456)},
 '1cse': {'chains': 'E,I', 'affinity': np.float64(16.07688302231306)},
 '3blh': {'chains': 'B,A', 'affinity': np.float64(8.894340827438068)},
 '5c0s': {'chains': 'HL,A', 'affinity': np.float64(11.063262037349798)},
 '1n8z': {'chains': 'AB,C', 'affinity': np.float64(12.112139388037868)},
 '3qs7': {'chains': 'EF,AB', 'affinity': np.float64(10.08753993866267)},
 '2iyb': {'chains': 'A,E', 'affinity': np.float64(7.422811738556569)},
 '4gn5': {'chains': 'A,D', 'affinity': np.float64(10.2365765761861)},
 '3idc': {'chains': 'B,A', 'affinity': np.float64(12.574550139770588)},
 '1sgy': {'chains': 'E,I', 'affinity': np.float64(12.804913828487024)},
 '5jtq': {'chains': 'EF,ABCD', 'affinity': np.float64(7.360418624665037)},
 '2ypv': {'chains': 'HL,A', 'affinity': np.float64(14.348583455433332)},
 '4lyl': {'chains': 'B,A', 'affinity': np.float64(10.238483781921817)},
 '6jbt': {'chains': 'HL,F', 'affinity': np.float64(12.939447480443365)},
 '4bfi': {'chains': 'A,B', 'affinity': np.float64(8.48386816877414)},
 '3qbt': {'chains': 'A,B', 'affinity': np.float64(8.243757055884426)},
 '2l2l': {'chains': 'B,A', 'affinity': np.float64(10.781099121592774)},
 '5vob': {'chains': 'HL,BD', 'affinity': np.float64(13.395495457098448)},
 '2xdf': {'chains': 'CD,AB', 'affinity': np.float64(6.378437731769002)},
 '3sdc': {'chains': 'AB,CD', 'affinity': np.float64(6.778290426241281)},
 '5wb8': {'chains': 'BC,AD', 'affinity': np.float64(7.571636842993602)},
 '1avx': {'chains': 'A,B', 'affinity': np.float64(15.306980924239491)},
 '2iff': {'chains': 'HL,Y', 'affinity': np.float64(10.908485255990527)},
 '3zuv': {'chains': 'B,A', 'affinity': np.float64(9.451949040551083)},
 '1fc2': {'chains': 'C,D', 'affinity': np.float64(10.548318586655956)},
 '3da7': {'chains': 'D,A', 'affinity': np.float64(9.389555926659554)},
 '4qxa': {'chains': 'B,A', 'affinity': np.float64(8.856121962670883)},
 '3lhp': {'chains': 'HL,S', 'affinity': np.float64(14.779484450374436)},
 '1taw': {'chains': 'B,A', 'affinity': np.float64(14.588694568323046)},
 '4zs7': {'chains': 'HL,A', 'affinity': np.float64(14.559801673761896)},
 '3tgk': {'chains': 'E,I', 'affinity': np.float64(6.709834853111396)},
 '6i07': {'chains': 'D,Bb', 'affinity': np.float64(10.908485255990527)},
 '3f7p': {'chains': 'C,A', 'affinity': np.float64(5.876679064652392)},
 '4hlz': {'chains': 'IJ,CD', 'affinity': np.float64(11.861573254325416)},
 '5wql': {'chains': 'C,A', 'affinity': np.float64(10.908485255990527)},
 '2roz': {'chains': 'A,B', 'affinity': np.float64(8.856121962670883)},
 '4wuu': {'chains': 'DE,AC', 'affinity': np.float64(10.74407538713855)},
 '1f47': {'chains': 'A,B', 'affinity': np.float64(6.361755308338998)},
 '1tmg': {'chains': 'E,I', 'affinity': np.float64(14.684936144347748)},
 '4jlr': {'chains': 'HL,S', 'affinity': np.float64(14.35056070891991)},
 '3onl': {'chains': 'C,AB', 'affinity': np.float64(6.709834853111396)},
 '4lad': {'chains': 'B,A', 'affinity': np.float64(10.117915154070571)},
 '3bky': {'chains': 'HL,P', 'affinity': np.float64(9.466103626364422)},
 '4gms': {'chains': 'JN,E', 'affinity': np.float64(10.498012597326598)},
 '5k22': {'chains': 'B,A', 'affinity': np.float64(10.36586991631957)},
 '4hff': {'chains': 'B,A', 'affinity': np.float64(13.049613268721338)},
 '4u5w': {'chains': 'BD,AC', 'affinity': np.float64(7.608728805671772)},
 '4eo5': {'chains': 'BC,A', 'affinity': np.float64(11.748690380386826)},
 '2omw': {'chains': 'B,A', 'affinity': np.float64(6.81780328499408)},
 '1j2j': {'chains': 'A,B', 'affinity': np.float64(8.082825707008016)},
 '3npz': {'chains': 'A,BC', 'affinity': np.float64(7.501887275878104)},
 '4qxt': {'chains': 'AB,Q', 'affinity': np.float64(10.630155278333628)},
 '1lfd': {'chains': 'A,B', 'affinity': np.float64(8.098598754921916)},
 '1jtd': {'chains': 'A,B', 'affinity': np.float64(15.210508728050858)},
 '2h9g': {'chains': 'HL,S', 'affinity': np.float64(11.318957914654456)},
 '1c9p': {'chains': 'B,A', 'affinity': np.float64(12.272045912989345)},
 '2a9k': {'chains': 'A,B', 'affinity': np.float64(10.045699204815364)},
 '1shy': {'chains': 'A,B', 'affinity': np.float64(9.607317712883242)},
 '4rwt': {'chains': 'D,A', 'affinity': np.float64(9.051686753256805)},
 '2p43': {'chains': 'B,A', 'affinity': np.float64(10.505244934018734)},
 '3osl': {'chains': 'B,A', 'affinity': np.float64(11.923966368216943)},
 '2j1k': {'chains': 'C,T', 'affinity': np.float64(12.215604476020047)},
 '3di3': {'chains': 'B,A', 'affinity': np.float64(10.469119702765449)},
 '3di2': {'chains': 'B,A', 'affinity': np.float64(6.469723740221682)},
 '5xbf': {'chains': 'B,A', 'affinity': np.float64(7.867132859353668)},
 '2jcc': {'chains': 'ABC,EF', 'affinity': np.float64(6.562107407689421)},
 '3v96': {'chains': 'B,A', 'affinity': np.float64(12.215604476020047)},
 '5lxm': {'chains': 'D,A', 'affinity': np.float64(9.196845054219311)},
 '1z7x': {'chains': 'W,X', 'affinity': np.float64(19.803155259042864)},
 '2sic': {'chains': 'E,I', 'affinity': np.float64(14.243923364499867)},
 '6flb': {'chains': 'HL,G', 'affinity': np.float64(12.272045912989345)},
 '4etp': {'chains': 'B,A', 'affinity': np.float64(8.77014708281506)},
 '3g3b': {'chains': 'B,A', 'affinity': np.float64(10.18378151468737)},
 '2p5e': {'chains': 'ABC,DE', 'affinity': np.float64(14.073966260277263)},
 '4kbb': {'chains': 'C,A', 'affinity': np.float64(9.196845054219311)},
 '3vpj': {'chains': 'E,A', 'affinity': np.float64(11.66869790837514)},
 '4r8w': {'chains': 'HL,AB', 'affinity': np.float64(13.27773858964528)},
 '4oqt': {'chains': 'HL,A', 'affinity': np.float64(14.046079228652088)},
 '1gla': {'chains': 'G,F', 'affinity': np.float64(7.979103451122048)},
 '1ahw': {'chains': 'AB,C', 'affinity': np.float64(11.547342171686186)},
 '4kro': {'chains': 'A,B', 'affinity': np.float64(8.943718321374119)},
 '6bkc': {'chains': 'HL,E', 'affinity': np.float64(12.404188593996372)},
 '2ktf': {'chains': 'A,B', 'affinity': np.float64(6.32456543925917)},
 '1kac': {'chains': 'A,B', 'affinity': np.float64(9.795369980333252)},
 '6d6u': {'chains': 'KL,D', 'affinity': np.float64(11.201201047201293)},
 '5u8q': {'chains': 'HL,A', 'affinity': np.float64(7.6629228514462815)},
 '5fo9': {'chains': 'F,DE', 'affinity': np.float64(7.8012664987368705)},
 '6j6y': {'chains': 'BC,A', 'affinity': np.float64(12.985022798434516)},
 '2lnh': {'chains': 'BC,A', 'affinity': np.float64(10.08753993866267)},
 '3c4p': {'chains': 'B,A', 'affinity': np.float64(11.39465915869219)},
 '4ala': {'chains': 'HL,C', 'affinity': np.float64(12.719160373253835)},
 '4msm': {'chains': 'B,A', 'affinity': np.float64(7.530780170439253)},
 '4yyp': {'chains': 'B,A', 'affinity': np.float64(8.935197499992418)},
 '5ma6': {'chains': 'B,A', 'affinity': np.float64(12.979130343160318)},
 '2voh': {'chains': 'B,A', 'affinity': np.float64(12.272045912989345)},
 '3btw': {'chains': 'E,I', 'affinity': np.float64(9.286080018091344)},
 '3gni': {'chains': 'B,A', 'affinity': np.float64(10.800516824107843)},
 '3ff7': {'chains': 'AB,CD', 'affinity': np.float64(5.043769969331335)},
 '6uys': {'chains': 'B,A', 'affinity': np.float64(7.903033964335996)},
 '3dvm': {'chains': 'B,A', 'affinity': np.float64(11.405525277670334)},
 '5tru': {'chains': 'HL,C', 'affinity': np.float64(10.873979173724171)},
 '4wv1': {'chains': 'AB,C', 'affinity': np.float64(11.706204581993257)},
 '4fp8': {'chains': 'HL,A', 'affinity': np.float64(8.681151935513585)},
 '1kxt': {'chains': 'B,A', 'affinity': np.float64(9.038951060921317)},
 '6cxg': {'chains': 'A,HL', 'affinity': np.float64(11.891948469733318)},
 '4yl8': {'chains': 'B,A', 'affinity': np.float64(7.182700625666856)},
 '2aeq': {'chains': 'HL,A', 'affinity': np.float64(10.800516824107843)},
 '5vmo': {'chains': 'B,A', 'affinity': np.float64(8.252373245149267)},
 '3l5n': {'chains': 'M,AB', 'affinity': np.float64(9.196845054219311)},
 '6her': {'chains': 'B,A', 'affinity': np.float64(10.08753993866267)},
 '4f37': {'chains': 'HL,A', 'affinity': np.float64(11.26251647768516)},
 '1dzb': {'chains': 'Aa,X', 'affinity': np.float64(8.572923668363236)},
 '1u0i': {'chains': 'B,A', 'affinity': np.float64(9.756142817320276)},
 '4e42': {'chains': 'B,A', 'affinity': np.float64(4.803658856441621)},
 '5ush': {'chains': 'DE,A', 'affinity': np.float64(12.03193480009963)},
 '5w06': {'chains': 'HL,T', 'affinity': np.float64(13.436352129652796)},
 '6b9j': {'chains': 'AB,Y', 'affinity': np.float64(12.893736789981835)},
 '4h6j': {'chains': 'B,A', 'affinity': np.float64(9.164827155735686)},
 '4ds8': {'chains': 'B,A', 'affinity': np.float64(6.972580066353349)},
 '3u7y': {'chains': 'HL,G', 'affinity': np.float64(9.26659462133481)},
 '4cj0': {'chains': 'B,A', 'affinity': np.float64(9.556888376984912)},
 '3rpg': {'chains': 'C,AB', 'affinity': np.float64(7.228275943658009)},
 '5ma4': {'chains': 'A,B', 'affinity': np.float64(14.02285323732696)},
 '6r2s': {'chains': 'C,AB', 'affinity': np.float64(14.588694568323046)},
 '1e6j': {'chains': 'HL,P', 'affinity': np.float64(10.277977538180489)},
 '4kv5': {'chains': 'EG,CD', 'affinity': np.float64(11.957814830350117)},
 '6mnr': {'chains': 'HL,P', 'affinity': np.float64(12.16407748110666)},
 '4why': {'chains': 'MN,B', 'affinity': np.float64(11.048076926649411)},
 '1eja': {'chains': 'B,A', 'affinity': np.float64(12.272045912989345)},
 '6ch3': {'chains': 'B,A', 'affinity': np.float64(6.81780328499408)},
 '1ct4': {'chains': 'E,I', 'affinity': np.float64(11.465469361013744)},
 '5wgg': {'chains': 'B,A', 'affinity': np.float64(8.39258216032146)},
 '4pc0': {'chains': 'C,A', 'affinity': np.float64(9.134451940327782)},
 '4nl9': {'chains': 'C,A', 'affinity': np.float64(9.004682756963348)},
 '5men': {'chains': 'DE,ABC', 'affinity': np.float64(6.093099543690923)},
 '2wy2': {'chains': 'D,ABC', 'affinity': np.float64(3.93531329866429)},
 '1m10': {'chains': 'A,B', 'affinity': np.float64(11.271580286353476)},
 '2b42': {'chains': 'A,B', 'affinity': np.float64(12.170408983929176)},
 '4tq0': {'chains': 'B,A', 'affinity': np.float64(7.037542324704344)},
 '4m1d': {'chains': 'IM,Q', 'affinity': np.float64(10.41524741025562)},
 '5e6j': {'chains': 'BC,A', 'affinity': np.float64(6.706390466098559)},
 '6ieb': {'chains': 'A,HL', 'affinity': np.float64(10.544180398477804)},
 '6q0o': {'chains': 'BZ,A', 'affinity': np.float64(8.723979281663853)},
 '2w84': {'chains': 'B,A', 'affinity': np.float64(9.756142817320276)},
 '5i5k': {'chains': 'XY,A', 'affinity': np.float64(14.664395812360782)},
 '4ml7': {'chains': 'B,A', 'affinity': np.float64(13.047415912326048)},
 '1xg2': {'chains': 'B,A', 'affinity': np.float64(11.318957914654456)},
 '4exp': {'chains': 'X,A', 'affinity': np.float64(8.591836600656825)},
 '2wo2': {'chains': 'B,A', 'affinity': np.float64(6.772227967002927)},
 '1wpx': {'chains': 'B,A', 'affinity': np.float64(11.923966368216943)},
 '4cmm': {'chains': 'B,A', 'affinity': np.float64(8.313506622999926)},
 '4bsr': {'chains': 'CD,AB', 'affinity': np.float64(11.861573254325416)},
 '4zgy': {'chains': 'B,A', 'affinity': np.float64(8.39258216032146)},
 '4pj9': {'chains': 'AB,CD', 'affinity': np.float64(7.6629228514462815)},
 '3d39': {'chains': 'ABC,DE', 'affinity': np.float64(8.445649304006954)},
 '2vlo': {'chains': 'A,B', 'affinity': np.float64(16.430408415762916)},
 '4v3k': {'chains': 'E,FD', 'affinity': np.float64(8.230741435928945)},
 '3n4i': {'chains': 'A,B', 'affinity': np.float64(12.236100456684513)},
 '4pjc': {'chains': 'AB,EF', 'affinity': np.float64(7.331525730103889)},
 '5nvn': {'chains': 'B,A', 'affinity': np.float64(9.898955820686346)},
 '5xco': {'chains': 'A,B', 'affinity': np.float64(10.977495051780496)},
 '4pp8': {'chains': 'CD,AB', 'affinity': np.float64(8.608654396557203)},
 '3a6b': {'chains': 'HL,Y', 'affinity': np.float64(9.581432584351486)},
 '1vfb': {'chains': 'AB,C', 'affinity': np.float64(11.05679114174405)},
 '4pjb': {'chains': 'AB,EF', 'affinity': np.float64(6.873652830990486)},
 '2j5l': {'chains': 'BC,A', 'affinity': np.float64(9.69970138035098)},
 '2h4m': {'chains': 'C,A', 'affinity': np.float64(10.05864704410152)},
 '4elm': {'chains': 'GH,AB', 'affinity': np.float64(7.1222847652619)},

In [ ]:
import os

pdb_list = [x.split('.')[0] for x in os.listdir('../../GraPPI_data/curated_db/unmut_sthg_esm_8A/') if x.endswith('.pkl')]

In [19]:
common_pdbs = set(pdb_list).intersection(set(testset.keys()))
diff_pdbs = set(testset.keys()).difference(set(pdb_list))

In [20]:
len(common_pdbs), len(diff_pdbs)

(512, 99)

In [24]:
'1ahw'.upper() in pdb_list

True

In [22]:
diff_pdbs

{'1ahw',
 '1avx',
 '1cse',
 '1ct4',
 '1dqj',
 '1e4k',
 '1eer',
 '1emv',
 '1f47',
 '1f6m',
 '1fc2',
 '1ffw',
 '1fle',
 '1fss',
 '1gla',
 '1h1v',
 '1j2j',
 '1jrh',
 '1jtd',
 '1k8r',
 '1kac',
 '1kkl',
 '1lfd',
 '1m10',
 '1mwa',
 '1n8z',
 '1nb5',
 '1qa9',
 '1rlb',
 '1s0w',
 '1s78',
 '1sgq',
 '1sgy',
 '1smf',
 '1tm7',
 '1tmg',
 '1vfb',
 '1xqs',
 '1yqv',
 '1yvb',
 '1z7x',
 '2a9k',
 '2ajf',
 '2b0z',
 '2b12',
 '2b42',
 '2ccl',
 '2dsq',
 '2g2u',
 '2j1k',
 '2jby',
 '2jcc',
 '2jel',
 '2ny7',
 '2oi9',
 '2oor',
 '2oza',
 '2p5e',
 '2sic',
 '2vlo',
 '2vlp',
 '2vn5',
 '2yj1',
 '3a4s',
 '3btw',
 '3dxa',
 '3e3q',
 '3ehu',
 '3k75',
 '3kbh',
 '3n4i',
 '3o4l',
 '3ssb',
 '3tgk',
 '3u7y',
 '3u82',
 '4bfi',
 '4e42',
 '4e6k',
 '4fp8',
 '4ftv',
 '4hsa',
 '4iz7',
 '4kro',
 '4kvn',
 '4nkq',
 '4nm8',
 '4ofy',
 '4u6h',
 '4v3k',
 '4y61',
 '5c6t',
 '5cyk',
 '5e9d',
 '5eiv',
 '5gpg',
 '5o14',
 '5ufe',
 '5xco'}

In [34]:
with open('./testset_list.json', 'w') as f:
    json.dump(testset, f, indent=4)

Please use this test dataset of PDB names and corresponding binding affinities for other models.  
Please download the repositories of models: [**ProAffinity-GNN**](https://pubs.acs.org/doi/full/10.1021/acs.jcim.4c01850) and [**PPI-Graphomer**](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-025-06123-2).  
Use the test data set above for the two models and get their Pearson coefficients (Rp) of their model prediction vs the true binding affinity.  
Please note that the binding affinities in PPI-Graphomer model are negative. Please be careful calculating the Rp for this model.