# Get test random mut table

In [46]:
import pandas as pd
import json

In [47]:
rand_mut_df = pd.read_csv('./saved_tables/rand_mut_table.csv')
with open('../../GraPPI_data/trained_data_ssl_finetune/2layers_10hdim_esm_jkmean/classifier_split_info.json') as f:
    split_info = json.load(f)

In [48]:
rand_mut_df = rand_mut_df [['PDB','Ligand Chains','Receptor Chains','new_pdb_name', 'mut_paths']]

In [49]:
rand_mut_df

,PDB,Ligand Chains,Receptor Chains,new_pdb_name,mut_paths
0,10LG,B,A,10lg_mut,PDB/rand_mut_pdbs/10lg_mut.pdb
1,12AS,B,A,12as_mut,PDB/rand_mut_pdbs/12as_mut.pdb
2,1A0N,B,A,1a0n_mut,PDB/rand_mut_pdbs/1a0n_mut.pdb
3,1A2X,B,A,1a2x_mut,PDB/rand_mut_pdbs/1a2x_mut.pdb
4,1A4I,B,A,1a4i_mut,PDB/rand_mut_pdbs/1a4i_mut.pdb
...,...,...,...,...,...
8550,9YC3,B,A,9yc3_mut,PDB/rand_mut_pdbs/9yc3_mut.pdb
8551,9YRO,B,A,9yro_mut,PDB/rand_mut_pdbs/9yro_mut.pdb
8552,9YTZ,C,E,9ytz_mut,PDB/rand_mut_pdbs/9ytz_mut.pdb
8553,9Z5Q,B,A,9z5q_mut,PDB/rand_mut_pdbs/9z5q_mut.pdb
8554,9ZZV,B,A,9zzv_mut,PDB/rand_mut_pdbs/9zzv_mut.pdb

In [50]:
# get key value with item == "random_mut" in the test negative sources
test_rand_mut_list = [key for key, value in split_info['test_neg_sources'].items() if value == "random_mut"]
print(len(test_rand_mut_list), test_rand_mut_list[:5])

1022 ['8uo9_mut', '8xez_mut', '5lwk_mut', '4gft_mut', '8xk2_mut']

In [51]:
sub_df = rand_mut_df[rand_mut_df['new_pdb_name'].isin(test_rand_mut_list)]
sub_df

,PDB,Ligand Chains,Receptor Chains,new_pdb_name,mut_paths
2,1A0N,B,A,1a0n_mut,PDB/rand_mut_pdbs/1a0n_mut.pdb
3,1A2X,B,A,1a2x_mut,PDB/rand_mut_pdbs/1a2x_mut.pdb
7,1A7T,B,A,1a7t_mut,PDB/rand_mut_pdbs/1a7t_mut.pdb
12,1AAP,B,A,1aap_mut,PDB/rand_mut_pdbs/1aap_mut.pdb
27,1AWC,B,A,1awc_mut,PDB/rand_mut_pdbs/1awc_mut.pdb
...,...,...,...,...,...
8529,9V8D,B,A,9v8d_mut,PDB/rand_mut_pdbs/9v8d_mut.pdb
8536,9VZ0,I,H,9vz0_mut,PDB/rand_mut_pdbs/9vz0_mut.pdb
8539,9WLP,A,B,9wlp_mut,PDB/rand_mut_pdbs/9wlp_mut.pdb
8540,9WNO,B,A,9wno_mut,PDB/rand_mut_pdbs/9wno_mut.pdb
8549,9Y7D,C,B,9y7d_mut,PDB/rand_mut_pdbs/9y7d_mut.pdb

In [52]:
# change mut_paths name to paths for sub_df
sub_df = sub_df.rename(columns={'mut_paths': 'paths'})

In [53]:
sub_df

,PDB,Ligand Chains,Receptor Chains,new_pdb_name,paths
2,1A0N,B,A,1a0n_mut,PDB/rand_mut_pdbs/1a0n_mut.pdb
3,1A2X,B,A,1a2x_mut,PDB/rand_mut_pdbs/1a2x_mut.pdb
7,1A7T,B,A,1a7t_mut,PDB/rand_mut_pdbs/1a7t_mut.pdb
12,1AAP,B,A,1aap_mut,PDB/rand_mut_pdbs/1aap_mut.pdb
27,1AWC,B,A,1awc_mut,PDB/rand_mut_pdbs/1awc_mut.pdb
...,...,...,...,...,...
8529,9V8D,B,A,9v8d_mut,PDB/rand_mut_pdbs/9v8d_mut.pdb
8536,9VZ0,I,H,9vz0_mut,PDB/rand_mut_pdbs/9vz0_mut.pdb
8539,9WLP,A,B,9wlp_mut,PDB/rand_mut_pdbs/9wlp_mut.pdb
8540,9WNO,B,A,9wno_mut,PDB/rand_mut_pdbs/9wno_mut.pdb
8549,9Y7D,C,B,9y7d_mut,PDB/rand_mut_pdbs/9y7d_mut.pdb

In [55]:
sub_df.to_csv('./saved_tables/test_rand_mut_table.csv', index=False)

# Get test df for positive

In [16]:
with open('../../GraPPI_data/trained_data_ssl_finetune/2layers_10hdim_esm_jkmean/classifier_split_info.json') as f:
    split_info = json.load(f)
wt_df = pd.read_csv('./saved_tables/wt_table.csv')
dimer_df = pd.read_csv('./saved_tables/dimer_table.csv')
# Combine wild-type and dimer dataframes into a single positive dataframe, if PDB column have repeat rows, just use wt_df's entries
posi_df = pd.concat([wt_df, dimer_df], ignore_index=True)
posi_df = posi_df.drop_duplicates(subset='PDB', keep='first')
len(posi_df)

11785

In [20]:
test_pos_name_list = split_info['test_pos_names']
# no matter upper or lower case
test_pos_name_list = [name.upper() for name in test_pos_name_list]
posi_df['PDB'] = posi_df['PDB'].str.upper()
sub_test_pos_df = posi_df[posi_df['PDB'].isin(test_pos_name_list)]
sub_test_pos_df

,PDB,Receptor Chains,Ligand Chains,paths,affinity
7,1B2U,D,A,../../GraPPI_data/PDB/SKEMPI_v2.0/1B2U.pdb,9.544925
12,1BP3,B,A,../../GraPPI_data/PDB/SKEMPI_v2.0/1BP3.pdb,14.292142
14,1C1Y,B,A,../../GraPPI_data/PDB/SKEMPI_v2.0/1C1Y.pdb,8.073396
15,1C4Z,D,"A, B, C",../../GraPPI_data/PDB/SKEMPI_v2.0/1C4Z.pdb,7.228276
23,1CZ8,"V, W","H, L",../../GraPPI_data/PDB/SKEMPI_v2.0/1CZ8.pdb,13.507759
...,...,...,...,...,...
11774,6XUE,A,B,../../GraPPI_data/PDB/old_dimer_db/6XUE.pdb,1.000000
11775,6XZ4,A,B,../../GraPPI_data/PDB/old_dimer_db/6XZ4.pdb,1.000000
11780,6ZIO,A,B,../../GraPPI_data/PDB/old_dimer_db/6ZIO.pdb,1.000000
11786,7CKF,A,B,../../GraPPI_data/PDB/old_dimer_db/7CKF.pdb,1.000000
11787,7NBI,A,B,../../GraPPI_data/PDB/old_dimer_db/7NBI.pdb,1.000000

In [ ]:
sub_test_pos_df.to_csv('./saved_tables/test_posi_df.csv', index=False)

# Get test df for preppi

In [23]:
with open('../../GraPPI_data/trained_data_ssl_finetune/2layers_10hdim_esm_jkmean/classifier_split_info.json') as f:
    split_info = json.load(f)
preppi_df = pd.read_csv('./saved_tables/preppi_db.csv')

In [27]:
test_preppi_list = [key for key, value in split_info['test_neg_sources'].items() if value == "preppi"]
# no matter upper or lower case
test_preppi_list = [name.upper() for name in test_preppi_list]
preppi_df['PDB'] = preppi_df['PDB'].str.upper()
sub_test_preppi_df = preppi_df[preppi_df['PDB'].isin(test_preppi_list)]
sub_test_preppi_df

,PDB,Receptor Chains,Ligand Chains,paths,affinity
54,M000025_M020443.59_480,A,B,../../GraPPI_data/preppi_aligned/M000025_M0204...,-1
68,M000263_M006180.30_140,A,B,../../GraPPI_data/preppi_aligned/M000263_M0061...,-1
70,M001846.1_159_M010637.73_137,A,B,../../GraPPI_data/preppi_aligned/M001846.1_159...,-1
72,M002217.1_89_M012330.30_191,A,B,../../GraPPI_data/preppi_aligned/M002217.1_89_...,-1
106,M000017_M015841.1417_1537,A,B,../../GraPPI_data/preppi_aligned/M000017_M0158...,-1
...,...,...,...,...,...
14931,M001075.110_203_M012181.1_137,A,B,../../GraPPI_data/preppi_aligned/M001075.110_2...,-1
14935,M000022_M008115.794_908,A,B,../../GraPPI_data/preppi_aligned/M000022_M0081...,-1
14944,M000333_M012690.26_142,A,B,../../GraPPI_data/preppi_aligned/M000333_M0126...,-1
14954,M000207_M019197,A,B,../../GraPPI_data/preppi_aligned/M000207_M0191...,-1
14996,M000597_M005513,A,B,../../GraPPI_data/preppi_aligned/M000597_M0055...,-1

In [28]:
sub_test_preppi_df.to_csv('./saved_tables/test_preppi_df.csv', index=False)