In [1]:
import pandas as pd

In [ ]:
AbEpiTope_df = pd.read_csv('./saved_tables/AbEpiTope_table.csv')
capri_df = pd.read_csv('./saved_tables/capri_all_table.csv')
dimer_df = pd.read_csv('./saved_tables/dimer_table.csv')
swapped_df = pd.read_csv('./saved_tables/swapped_table.csv')
wt_df = pd.read_csv('./saved_tables/wt_table.csv')
print(len(AbEpiTope_df),len(capri_df),len(dimer_df),len(swapped_df),len(wt_df), len(AbEpiTope_df)+len(capri_df)+len(dimer_df)+len(swapped_df)+len(wt_df))

272 3429 5038 3080 3098 14917

In [3]:
swapped_df

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,1Q68_r_4HGM_l,A,B,../../PDB/swap_pdbs/1Q68_r_4HGM_l.pdb,0
1,1Q68_r_3C4M_l,A,B,../../PDB/swap_pdbs/1Q68_r_3C4M_l.pdb,0
2,1Q68_r_1HE8_l,A,B,../../PDB/swap_pdbs/1Q68_r_1HE8_l.pdb,0
3,1Q68_r_2GYK_l,A,B,../../PDB/swap_pdbs/1Q68_r_2GYK_l.pdb,0
4,1Q68_l_2NYZ_r,A,B,../../PDB/swap_pdbs/1Q68_l_2NYZ_r.pdb,0
...,...,...,...,...,...
3075,2B4J_r_5HLZ_l,A,"B,C",../../PDB/swap_pdbs/2B4J_r_5HLZ_l.pdb,0
3076,2B4J_l_1G0V_r,A,"B,C",../../PDB/swap_pdbs/2B4J_l_1G0V_r.pdb,0
3077,2B4J_l_5CZF_r,A,"B,C",../../PDB/swap_pdbs/2B4J_l_5CZF_r.pdb,0
3078,2B4J_l_5UN7_r,A,"B,C",../../PDB/swap_pdbs/2B4J_l_5UN7_r.pdb,0
3079,2B4J_l_1T6B_r,A,"B,C",../../PDB/swap_pdbs/2B4J_l_1T6B_r.pdb,0

In [7]:
capri_df[capri_df['PDB'].str.contains('2j59')]

,PDB,Receptor Chains,Ligand Chains,paths,affinity
0,2j59,B,N,../../PDB/capri_wt/2J59.pdb,1.0
131,2j59_1_49,C,B,../../PDB/capri_fk/2j59_1_49.pdb,0.0
133,2j59_1_61,C,B,../../PDB/capri_fk/2j59_1_61.pdb,0.0
268,2j59_1_74,C,B,../../PDB/capri_fk/2j59_1_74.pdb,0.0
327,2j59_1_76,C,B,../../PDB/capri_fk/2j59_1_76.pdb,0.0
461,2j59_1_1,C,B,../../PDB/capri_fk/2j59_1_1.pdb,0.0
520,2j59_1_73,C,B,../../PDB/capri_fk/2j59_1_73.pdb,0.0
669,2j59_1_66,C,B,../../PDB/capri_fk/2j59_1_66.pdb,0.0
673,2j59_1_72,C,B,../../PDB/capri_fk/2j59_1_72.pdb,0.0
726,2j59_1_70,C,B,../../PDB/capri_fk/2j59_1_70.pdb,0.0
733,2j59_1_58,C,B,../../PDB/capri_fk/2j59_1_58.pdb,0.0
760,2j59_1_6,C,B,../../PDB/capri_fk/2j59_1_6.pdb,0.0
874,2j59_1_7,C,B,../../PDB/capri_fk/2j59_1_7.pdb,0.0
898,2j59_1_59,C,B,../../PDB/capri_fk/2j59_1_59.pdb,0.0
902,2j59_1_71,C,B,../../PDB/capri_fk/2j59_1_71.pdb,0.0
904,2j59_1_65,C,B,../../PDB/capri_fk/2j59_1_65.pdb,0.0
1307,2j59_1_14,C,B,../../PDB/capri_fk/2j59_1_14.pdb,0.0
1361,2j59_1_10,C,B,../../PDB/capri_fk/2j59_1_10.pdb,0.0
1696,2j59_1_12,C,B,../../PDB/capri_fk/2j59_1_12.pdb,0.0
1754,2j59_1_23,C,B,../../PDB/capri_fk/2j59_1_23.pdb,0.0
1880,2j59_1_36,C,B,../../PDB/capri_fk/2j59_1_36.pdb,0.0
2095,2j59_1_21,C,B,../../PDB/capri_fk/2j59_1_21.pdb,0.0
2170,2j59_1_31,C,B,../../PDB/capri_fk/2j59_1_31.pdb,0.0
2399,2j59_1_32,C,B,../../PDB/capri_fk/2j59_1_32.pdb,0.0
2624,2j59_1_40,C,B,../../PDB/capri_fk/2j59_1_40.pdb,0.0
2750,2j59_1_96,C,B,../../PDB/capri_fk/2j59_1_96.pdb,0.0
2764,2j59_1_55,C,B,../../PDB/capri_fk/2j59_1_55.pdb,0.0
2832,2j59_1_43,C,B,../../PDB/capri_fk/2j59_1_43.pdb,0.0
2844,2j59_1_94,C,B,../../PDB/capri_fk/2j59_1_94.pdb,0.0
2850,2j59_1_9,C,B,../../PDB/capri_fk/2j59_1_9.pdb,0.0
2977,2j59_1_56,C,B,../../PDB/capri_fk/2j59_1_56.pdb,0.0
3030,2j59_1_52,C,B,../../PDB/capri_fk/2j59_1_52.pdb,0.0
3178,2j59_1_84,C,B,../../PDB/capri_fk/2j59_1_84.pdb,0.0
3264,2j59_1_86,C,B,../../PDB/capri_fk/2j59_1_86.pdb,0.0
3267,2j59_1_92,C,B,../../PDB/capri_fk/2j59_1_92.pdb,0.0
3396,2j59_1_87,C,B,../../PDB/capri_fk/2j59_1_87.pdb,0.0